### ISSUE TITLE
"cargo install clippy" fails with nightly compiler

### ISSUE THREAD

**Issue by jonathandturner** [Manishearth/rust-clippy#1001]
When doing a "cargo install clippy" using the nightly compiler, I'm seeing:

```
   Compiling clippy_lints v0.0.75
error: unresolved import `rustc_const_math::ConstFloat`. There is no `ConstFloat` in `rustc_const_math` [--explain E0432]
 --> /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.75/src/misc.rs:9:5
  |>
9 |> use rustc_const_math::ConstFloat;
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: failed to resolve. Use of undeclared type or module `ConstFloat` [--explain E0433]
   --> /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.75/src/misc.rs:188:20
    |>
188 |>         let zero = ConstFloat::FInfer {
    |>                    ^^^^^^^^^^^^^^^^^^

error: failed to resolve. Use of undeclared type or module `ConstFloat` [--explain E0433]
   --> /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.75/src/misc.rs:193:24
    |>
193 |>         let infinity = ConstFloat::FInfer {
    |>                        ^^^^^^^^^^^^^^^^^^
```

Did I miss a step?

**Comment by oli-obk** [comment]
You probably need to update your nightly. Which version are you using?

**Comment by jonathandturner** [comment]
rustc 1.11.0-nightly (12238b984 2016-06-04)

**Comment by oli-obk** [comment]
That's about a week old. You definitely need to update ;) There were some changes wrt constant floats

**Comment by jonathandturner** [comment]
Oh hey, that did the trick.

To save the confusion for the next "me" who comes along, might want to drop a note to that effect in your docs (which you might have, but I didn't see)

**Comment by mcarton** [comment]
The first line of the Usage section is “Compiler plugins are highly unstable and will only work with a nightly Rust for now.”

“only work with a nightly Rust” is to be understood “only works on a *recent* nightly Rust” :smile:
