### ISSUE TITLE
Suggest `.get()` over `.iter().nth()`

### ISSUE THREAD

**Issue by mcarton** [Manishearth/rust-clippy#1009]
`.get()` exists on slices, which people (including me) seem not to be aware of (cc #1008).

**Comment by devonhollowood** [comment]
I can do this one, if that's okay.

**Comment by mcarton** [comment]
@devonhollowood great!
Don't hesitate to ask if you have any question.

**Comment by devonhollowood** [comment]
I went ahead and implemented the same check for `Vec`s. I hope that was okay. Pull request [here](https://github.com/Manishearth/rust-clippy/pull/1016).
