### ISSUE TITLE
speed up travis by only installing clippy and using the installed clippy to run the tests

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#1030]
Currently travis runs `cargo test`, which builds all of clippy and runs the test suite. Then after all that, it installs clippy and runs it once on itself.

We could probably set up something so travis runs `cargo install` and uses that binary for everything.

Might be a little fickle though, because we probably need an additional `clippy-tests` crate.

**Comment by killercup** [comment]
Why not just `cp target/release/cargo-clippy $some_bin_path` and call that?

**Comment by oli-obk** [comment]
Makes sense. We can assume that `cargo install` doesn't do anything else (except use release mode).
