### ISSUE TITLE
Advice for using rust nightly is misleading

### ISSUE THREAD

**Issue by bestouff** [Manishearth/rust-clippy#1035]
Hi,

The `README.md` suggests that rust nightly is required for running clippy as a compiler plugin, but not for using it as a cargo subcommand. Which is false of course, `cargo install clippy` has no chance to work with rust stable.
Would it be possible to fix the `README.md` to reflect that ? I can propose a patch if needs be.

**Comment by Manishearth** [comment]
Sure, go ahead!

**Comment by bestouff** [comment]
Fixed in #1036
