### ISSUE TITLE
Suggest ptr::null, ptr::null_mut over casting.

### ISSUE THREAD

**Issue by Stebalien** [Manishearth/rust-clippy#1047]
Add a lint to suggest converting all instances of:

``` rust
0 as *const T;
0 as *mut T;
```

To:

``` rust
std::ptr::null();
std::ptr::null_mut();
```

See https://github.com/rust-lang/rust/pull/34456

**Comment by oli-obk** [comment]
These are also in `core`. We should probably figure out whether `no_std` is set and suggest `core::ptr::*` in that case.

**Comment by mcarton** [comment]
> We should probably figure out whether `no_std` is set and suggest  `core::ptr::*` in that case.

This could be done for a lot a paths in suggestions.

**Comment by llogiq** [comment]
Sounds like we could use a utility function that walks the parent chain to look for `#[no_std]`.

**Comment by mcarton** [comment]
You don't even need to walk the parent chain, the current crate is available as `LateContext::krate` which has attributes.

**Comment by llogiq** [comment]
True. I had forgotten that this attribute is crate-level only.

**Comment by AndrewBrinker** [comment]
I'm happy to give this a shot.

**Comment by mcarton** [comment]
Great! Feel free to ask if you have any question.
