### ISSUE TITLE
CI builds for OS X and Windows

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#1056]
We should be able to build for OS X and Windows. [travis-rust-matrix](https://github.com/carllerche/travis-rust-matrix) has scripts to do this with travis and appveyor. This will also allow us to test builds for x86 systems, which come with less memory and hopefully find all system-specific flaws before our users find them. :smile:

**Comment by oli-obk** [comment]
Since we do not need to run anything on the target platform it would be enough to install the target (through rustup or some means). We do this in `miri` for all installed targets, but travis doesn't have additional targets, so it only happens when you test locally.
