### ISSUE TITLE
Warn about clone impls for Copy types

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#107]
The following is legal and totally weird/useless

```rust
#[derive(Copy)]
struct A;

impl Clone for A {
    fn clone(&self) -> A {
        panic!("bla");
    }
}

fn main() {
    let a = A;
    let b = a;
    let c = a.clone();
}
```

**Comment by llogiq** [comment]
It depends. Copy is usually shallow, while clone may copy data behind pointers – it's a deep copy.

To have both may be useful in some situations. Implementing clone by accident isn't terribly common, so I doubt the value proposition of such a lint.

**Comment by oli-obk** [comment]
To implement `Clone` on a
