### ISSUE TITLE
Suggest to store large enum variants as Box

### ISSUE THREAD

**Issue by DarkEld3r** [Manishearth/rust-clippy#1127]
For example:

``` rust
enum Test {
    A(i32),
    B([i32; 8000]),
}
```

In this case it probably would be better to use `B(Box<[i32; 8000]>)`.

**Comment by Manishearth** [comment]
Tip for anyone trying to solve this bug: https://github.com/Manishearth/rust-clippy/blob/04c8108e3f473dbe80b8e67e18e923c91c362b5e/clippy_lints/src/escape.rs#L194 contains some code that extracts the size of a type. Probably should extract that into utils, and use it.
