### ISSUE TITLE
Provide a cfg option for when Clippy is in use

### ISSUE THREAD

**Issue by DemiMarie** [Manishearth/rust-clippy#1133]
Clippy should define a way to selectively enable an attribute when Clippy is in use.  The attributes that control Clippy raise warnings about unknown lints when Clippy is not in use.  Since I use `#[deny(warnings)]`, these break the build.

Probably easiest to use a feature.

**Comment by Manishearth** [comment]
This isn't something clippy can define, it's something you have to define. Most people do `#[cfg_attr(feature=clippy, allow(some_clippy_lint))]`, etc

**Comment by DemiMarie** [comment]
Sorry, I meant to define a Cargo feature when cargo clippy is run.

**Comment by Manishearth** [comment]
We used to do that, but cargo errors if the feature doesn't exist, so this can't work for both people who have the feature and those who don't. The verdict was to just have people manually pass it to cargo clippy.

Might be possible with raw cfg though.

**Comment by mcarton** [comment]
@Manishearth what do you mean with “raw cfg”? It was one (as in “not a cargo feature”, it was a rustc cfg).

Cc #1057.

**Comment by Manishearth** [comment]
`cfg(feature=foo)` is a cargo feature, set by cargo. Cargo has restrictions on these features. `cfg(clippy)` is something we can set by passing `--cfg clippy` to rust. This will be silently ignored for crates that don't use it, unlike `--features clippy`

**Comment by mcarton** [comment]
The feature of #1057 was `--cfg feature=\"clippy\"`, which IIRC is what cargo does, but cargo wasn't aware of it.
We should check whether `--cfg clippy` poses the same problems `--cfg feature=\"clippy\"` did.
