### ISSUE TITLE
enum_variant_names: warn about prefix/postfix only if >N variants present

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#1138]
With enums that have only a few (2 or 3?) variants, the probability is large that the naming will not be improved by moving the common parts into the enum name.

An example is vulkano's `DeviceCreationError::OutOfHostMemory` and `DeviceCreationError::OutOfDeviceMemory` - it is a generic device creation error, not specifically an "out of memory on device creation" error, and it is incidental that the only two current cases are out-of-memory cases.

**Comment by oli-obk** [comment]
Sounds reasonable to me to exclude enums with few variants. The variant count should obviously be configurable

**Comment by Manishearth** [comment]
wfm
