### ISSUE TITLE
Warn against unnecessary lifetime parameters

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#115]
Wherever elision would work.

**Comment by llogiq** [comment]
Some people like to write out the lifetimes to get the hang of it. Do we really want to warn? Alas, there is no 'note' level...

**Comment by mgattozzi** [comment]
You could add #![deny(lifetime_warning)] if people really wanted to write out the lifetimes, but if elision works and someone has the lifetimes written out manually it would be more prudent to warn them about it if it's unecessary.

**Comment by llogiq** [comment]
You probably mean `#![allow(lifetime_warning)]`.

**Comment by mgattozzi** [comment]
Yeah much better wording.

**Comment by Manishearth** [comment]
> Some people like to write out the lifetimes to get the hang of it.

Elision mostly happens in the obvious cases where lifetimes are just noise.

E.g `fn(&a, &b, &c, &d) -> e` --> `fn(&'a a, &'b b, &'c c, &'d d) -> e`, and `fn(&a, b, c, d) -> &e` --> `fn(&'a a, b, c, d) -> &'a e`.

If anything, when you see a function with explicit lifetimes you start thinking that there's something funky going on (when there isn't)

**Comment by llogiq** [comment]
Ok, you've convinced me that Warn by default is a good idea. :smile:
