### ISSUE TITLE
Invalid needless return lint

### ISSUE THREAD

**Issue by Keats** [Manishearth/rust-clippy#1163]
Clippy version: 0.0.81
Running clippy on https://github.com/Keats/tera master I get 2 needless returns lint for the returns in those lines https://github.com/Keats/tera/blob/master/src/render.rs#L357-L371 but removing them gives a incompatible match arms type (`expected enum `std::result::Result`, found ()`).

To be honest I'm not entirely sure why I need the return to compile, it looks like it should work without

**Comment by llogiq** [comment]
It's likely you forgot to remove the semicolon at the end of the line.

**Comment by Keats** [comment]
Indeed, missed the `match` one, my bad!

**Comment by llogiq** [comment]
No problem, happens to the best of us.
