### ISSUE TITLE
Warn on loop-match-break, replace with while-let

### ISSUE THREAD

**Issue by Zarathustra30** [Manishearth/rust-clippy#118]
Loop-match-break constructs like this snippet [stolen from the benchmarks game](http://benchmarksgame.alioth.debian.org/u64q/program.php?test=nbody&lang=rust):
```
loop {
    let bi = match bodies.next() {
        Some(bi) => bi,
        None => break
    };
    ...
}
```
can be replaced with a simple `while let`:
```
while let Some(bi) = bodies.next() {
    ...
}
```
Loop-match-breaks don't do anything *bad*, but they decrease readability and make control flow more confusing.  Are there any cases where while-let would not suffice?

**Comment by llogiq** [comment]
If there is something unrelated between the loop and the match.

Apart from that we may also want to detect the same thing with if-let instead of match.
