### ISSUE TITLE
Suggest using is_null instead of comparing to ptr::null()

### ISSUE THREAD

**Issue by jminer** [Manishearth/rust-clippy#1184]
I would use a lint for comparing a pointer to `std::ptr::null()` or `std::ptr::null_mut()`, instead of using the inherent `is_null` method on pointers. It would lint on

    if(handle == ptr::null_mut()) {
    }

so that it could be changed to

    if(handle.is_null()) {
    }

**Comment by llogiq** [comment]
Good idea!

**Comment by llogiq** [comment]
I should note that this lint is still quite bare-bones. We may want to improve on it, e.g. add a suggestion.
