### ISSUE TITLE
Lint suggestion: Calling .ok() unnecessary in if let

### ISSUE THREAD

**Issue by Apanatshka** [Manishearth/rust-clippy#1185]
I just found myself committing this code:

```rust
        for result in iter {
            if let Some(bench) = try!(result).parse().ok() {
                vec.push(bench)
            }
        }
```

I felt silly, because the `.ok()` is unnecessary, I could have just matched on `Ok(bench)`:

```rust
        for result in iter {
            if let Ok(bench) = try!(result).parse() {
                vec.push(bench)
            }
        }
```

So I figured this might be a good lint.

**Comment by KitFreddura** [comment]
I'll try working on this!

**Comment by mcarton** [comment]
@KitFreddura Great! Let us know if you have any problem :smile:

**Comment by KitFreddura** [comment]
I think I'm getting the hang of clippy, but I can't seem to find the rustc::hir struct corresponding to an if let statement? ExprIf doesn't seem to be it, does anyone have any advice?

**Comment by llogiq** [comment]
if let gets desugared to a match

**Comment by mcarton** [comment]
@KitFreddura it's `ExprMatch` with `MatchSource::IfLetDesugar`. `hir` contains less stuff than `ast`.

**Comment by KitFreddura** [comment]
Oh awesome, thanks!

**Comment by Manishearth** [comment]
Fixed in https://github.com/Manishearth/rust-clippy/pull/1257
