### ISSUE TITLE
Make option_map_unwrap_or and option_map_unwrap_or_else allow by default

### ISSUE THREAD

**Issue by killercup** [Manishearth/rust-clippy#1192]
One of the lints I ignore most often is [option_map_unwrap_or](https://manishearth.github.io/rust-clippy/v0.0.84/#option_map_unwrap_or).

The docs say:

> **What it does:** Checks for usage of `_.map(_).unwrap_or(_).`
>
> **Why is this bad**: Readability, this can be written more concisely as `_.map_or(_, _).`

I think having two method calls with one parameter makes the intent clearer than using one with two parameters (one method call per line does one thing). This may also keep the diff-noise down a bit.

The same goes for option_map_unwrap_or_else.

**Comment by leodasvacas** [comment]
I've seen crates that disliked `map_or` so I'm in favor of this.

**Comment by Stebalien** [comment]
Worse, the argument order is confusing; personally, I'd lint *against* using this function. When I see `map_or_else`, I expect the first function to be the map function and the second to be the "else" function but it's actually backwards.
