### ISSUE TITLE
Warn on use of `+` for String

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#121]
I honestly think that the `Add` implementation for String was a mistake – it isn't symmetric even in type signature, and it consumes self, which is surprising to the newbie (who probably has the mental model of other languages, where a new String would be created).

So we should warn the newbie of this pitfall, and maybe suggest using [`String::push_str`](http://doc.rust-lang.org/std/string/struct.String.html#method.push_str) instead (perhaps only on self-assignment, like `s = s + "..."`)

**Comment by Manishearth** [comment]
++1 for a lint for `s = s + s2` where `s: String`


I'm not so sure on the generic string addition lint. On the face of it it looks good to me, but I'm wary of making clippy too opinionated.

There seems to be major support for this POV though, so I guess we should land it and perhaps remove it if anyone complains.

**Comment by llogiq** [comment]
Perhaps we should make it two lints, like `string_add_assign` (matching `s =s + ...`) and `string_add` (that warns on all string addition and disables the other lint).

I'm ok with having the second one allow by default if you want.

**Comment by Manishearth** [comment]
sgtm
