### ISSUE TITLE
Failure to build with Rust 1.4.0 Nightly

### ISSUE THREAD

**Issue by mgattozzi** [Manishearth/rust-clippy#123]
Clippy doesn't compile with rustc 1.4.0-nightly (a5d33d891 2015-08-08) giving the following error message:
```
2dcb0086/master/src/len_zero.rs:147:26: 147:28 error: mismatched types:
 expected `&syntax::ast::DefId`,
    found `&&rustc::middle::ty::AdtDefData<'_, 'static>`
(expected struct `syntax::ast::DefId`,
    found &-ptr) [E0308]
/home/michael/.multirust/toolchains/nightly/cargo/git/checkouts/rust-clippy-297222992dcb0086/master/src/len_zero.rs:147 			has_is_empty_impl(cx, id),
```

**Comment by llogiq** [comment]
Yeah, I just noticed that, too. The reason is that some rustc functions now return a `AdtDefData` (which contains the `DefId`) instead of a blank `DefId`. Should be easy to fix. I'll see if I find a few minutes this evening.
