### ISSUE TITLE
Add constant folding utility method

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#124]
We do some constant folding throughout the lints; it would be nice to have a constant folding function that takes an Expr and returns an `Option<Lit>`

**Comment by llogiq** [comment]
Agreed, let's either make a new `const.rs` or just put it in `utils.rs`.

**Comment by llogiq** [comment]
One more thing, we normally don't have or need a `span`, so the return type should be `Option<Lit_>`.

**Comment by Manishearth** [comment]
Sure, when I said `Lit` I mostly meant the inner enum, I use the AST nodes interchangeably with the enums when talking about them :)

**Comment by llogiq** [comment]
Open tasks to work on:

[ ] More casts
[ ] Struct and Field
[ ] Range
[ ] BinaryOp: Remainder
[ ] Box, UnOp:Uniq, UnOp:Deref, ExprAddrOf
[ ] Block / ExprRet handling (e.g. `const x = { return 1; }`)
[ ] enum variant retrieval

**Comment by llogiq** [comment]
I'm closing this. Const folding is a solved problem as far as I'm concerned.
