### ISSUE TITLE
"cargo install clippy" doesn't work on windows (version 0.0.93)

### ISSUE THREAD

**Issue by lukebitts** [Manishearth/rust-clippy#1260]
There is (I assume) a new folder under tests called "aux", that's a reserved name in Windows so "cargo install clippy --verbose" returns the following message:

     Updating registry `https://github.com/rust-lang/crates.io-index`
    error: failed to unpack package `clippy v0.0.93`

     Caused by:
     failed to create `C:\Users\[user]\.cargo\registry\src\github.com-1ecc6299db9ec823\clippy-0.0.93\tests\aux`

     Caused by:
     Directory name is invalid. (os error 267)

**Comment by mcarton** [comment]
Thanks for the report! This has been fixed in 0.0.94.
