### ISSUE TITLE
Could not compile `clippy_lints` v0.0.94

### ISSUE THREAD

**Issue by robertoggarcia** [Manishearth/rust-clippy#1263]
I try to run my Rust program and get this error:

error: type macros are experimental (see issue #27245)
Caused by:
  Could not compile `clippy_lints`.

Caused by:
  Process didn't exit successfully:  (exit code: 101)

**Comment by mcarton** [comment]
https://github.com/rust-lang/rust/issues/27245
e338f6a4f018021a2ffc2574991ec4c3b9329642
Are you using an old nightly compiler? (yeah, >1 month is old for a nightly)

**Comment by robertoggarcia** [comment]
Iam using rustc 1.12.0 (3191fbae9 2016-09-23)

**Comment by mcarton** [comment]
Well, that's it, [as stated in the readme](https://github.com/Manishearth/rust-clippy#usage) and [the template you removed before filling in the issue](https://raw.githubusercontent.com/Manishearth/rust-clippy/master/.github/ISSUE_TEMPLATE.md), clippy works on the *latest* Rust nightly.
Feel free to reopen an issue if you still have any problem after upgrading rustc.

**Comment by robertoggarcia** [comment]
Thanks

**Comment by mcandre** [comment]
It broke again :/

rustc 1.28.0-nightly (cb20f68d0 2018-05-21)
