### ISSUE TITLE
Lint idea: `Err(_)`

### ISSUE THREAD

**Issue by carols10cents** [Manishearth/rust-clippy#1270]
This is the 3rd scenario found by [this paper](https://blog.acolyer.org/2016/10/06/simple-testing-can-prevent-most-critical-failures/) that commonly causes critical failures: "Error handlers that catch an abstract exception type (e.g. Exception or Throwable in Java) and then take drastic action such as aborting the system."

Now, I don't know if this directly translates. And I think the result_unwrap_used and option_unwrap_used lints catch the most common ways of doing this in Rust! But there's another way, and I don't know if this is common enough to justify a lint:

``` rust
match something {
    Ok(stuff) => { 
        // happy path stuff
    },
    Err(_) => {
        panic!("stop the world");
    },
}    
```

the key parts being the matching of any type of error, and the drastic action in the `Err` arm.

Again, please do close this if this doesn't seem like a worthwhile idea!! <3

**Comment by oli-obk** [comment]
We should probably be allowing `unreachable!` here.

**Comment by bood** [comment]
I'll take a look at this one. Maybe `panic!` should also be allowed? @oli-obk

**Comment by oli-obk** [comment]
@bood: I think the lint is intended to only trigger if the arm is `Err(_)` and the content ends with a `panic!`, but not if the panic is inside an `unreachable!`. Or maybe even disallow all diverging calls except `unreachable!()`. We'll need to tread carefully here, since it has the potential for lots of false positives.

**Comment by bood** [comment]
@oli-obk Any hints on how to match an `unreachable!` call?
Since macro is no longer visible in AST tree, I would:
1. match a call (and it's the only statement in the block)
2. get the text from the call span and compare against `unreachable!`
Not sure if it's a best way though. Please advise.

**Comment by oli-obk** [comment]
See [these two](https://github.com/Manishearth/rust-clippy/blob/master/clippy_lints/src/utils/mod.rs#L670-L702) functions for how to check whether a piece of code comes from a specific macro.

**Comment by bood** [comment]
Got it.
Another confusion is about `rustc::hir` and `syntax::ast`. When I was working on `formatting.rs` before, `ast` is used for matching nodes. However, in `matches.rs` here, `arm[0].body.node` seems to be a `rustc::hir::ExprBlock`. My confuse is:
1. what is the difference between the two module? is there a preferring when to use which?
2. is there a way I can convert between the structures in two modules?

**Comment by oli-obk** [comment]
These are inherently incompatible. If you are using a `LateLintPass`, you need to use the `hir`, if you are using an `EarlyLintPass`, you need to use the `ast`.

**Comment by mcarton** [comment]
> is there a preferring when to use which? 
`ast` tends to be simpler and more stable so usually if it's possible, go for it. `hir` however is more powerful, names, types, functions, modules, constants, etc. have all be resolved and we can use that information.

> is there a way I can convert between the structures in two modules?
No. Note that this would rarely be useful as almost all information in `ast` is also available in `hir`.
