### ISSUE TITLE
redundant multiple pattern suggested when one pattern is _

### ISSUE THREAD

**Issue by tspiteri** [Manishearth/rust-clippy#1272]
pub enum E {
        A,
        B,
        C,
    }
    pub fn foo(e: E) -> i32 {
        match e {
            E::A => 0,
            E::B => 1,
            _ => 0,
        }
    }

clippy suggests refactoring into `E::A | _`, but in this case, the `E::A` arm is just redundant.

**Comment by mcarton** [comment]
In that case it would be even better to suggest `E::A | E::C` but I guess to keep it simple `_` is enough.
