### ISSUE TITLE
"cargo help clippy" shows help for cargo rustc ten times

### ISSUE THREAD

**Issue by bluss** [Manishearth/rust-clippy#1283]
"cargo help clippy" shows help for cargo rustc ten times.

It's helpful, but it's not helping. :smile:

**Comment by oli-obk** [comment]
I assume by "ten" you mean the number of targets that `cargo clippy` would check.

We should not forward the help to `cargo rustc`, but instead print something useful.

**Comment by bluss** [comment]
Right, I think I maybe have ten targets. I would like to use the help button to find out how to only run clippy for the library itself. Cargo test has a `--lib` flag, so it might be worth copying.
