### ISSUE TITLE
Un-revert the `clippy` feature

### ISSUE THREAD

**Issue by mcarton** [Manishearth/rust-clippy#1286]
I'd like to revert #1057, which reverted #996.

The name `clippy` was to generic and conflicted with people's already existing usage. Someone just asked for something like that on IRC, and I'd like to bring that under another name. Maybe `cargo-clippy` if it appears that it's not being used. I'll have to check on crates.io or github.

Do you think it's a good idea? Are you ok with `cargo-clippy`?

**Comment by Manishearth** [comment]
I'd be very careful about this. cargo-clippy sounds okay to me though

**Comment by mcarton** [comment]
A quick search on GitHub suggests that `cargo-clippy` is not used:

* [`clippy`]: 635 code results
* [`cargo-clippy`]: only a few false-positive

[`clippy`]: https://github.com/search?q=%23![cfg_attr(feature="clippy",+plugin(clippy))]&type=Code&utf8=✓
[`cargo-clippy`]: https://github.com/search?q=%23![cfg_attr(feature="cargo-clippy",+plugin(clippy))]&ref=opensearch&type=Code
