### ISSUE TITLE
lint unnecessary iteration

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#1292]
rustc code contained `slice.iter().cloned().collect()`, which should be `slice.to_owned()`.

is probably just another extension to https://github.com/Manishearth/rust-clippy/blob/master/clippy_lints/src/methods.rs#L502

**Comment by F001** [comment]
I'd like to take my first shot on this rule.

Note: Slice's `to_owned()` method always returns `Vec<T>`. If the target type of `collect()` is not `Vec`, it is not a defect.

**Comment by sinkuu** [comment]
Why not [`slice::to_vec`](https://doc.rust-lang.org/std/primitive.slice.html#method.to_vec)? Its name is more clear than `to_owned` when reading code.

**Comment by F001** [comment]
Good suggestion. I have updated the suggestion to `to_vec`.
