### ISSUE TITLE
Add a lint to prefer expect("<justification>") over unwrap()

### ISSUE THREAD

**Issue by fitzgen** [Manishearth/rust-clippy#1298]
It would be super cool to have a lint that disallows/warns on `unwrap()` and tells users to use `expect("some kind of justification why this is OK")`.

**Comment by mcarton** [comment]
There already is :smile:
https://github.com/Manishearth/rust-clippy/wiki#option_unwrap_used
https://github.com/Manishearth/rust-clippy/wiki#result_unwrap_used

**Comment by fitzgen** [comment]
Great, thanks! 😸
