### ISSUE TITLE
HashMap::keys() and HashMap::values()

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#13]
Use `.keys()` and `.values()` instead of  `for (_, value) in hashmap.iter() or for (key, _) in hashmap.iter()`

**Comment by llogiq** [comment]
I think the problematic case is if one iterates over `.keys()` and then uses `.get(key)` to get the corresponding values.

Or am I missing something? Is `for (key, _) in hashmap.iter()` somehow faster or better than `for key in hashmap.keys()`? For what it's worth, I think the latter is more readable.
