### ISSUE TITLE
Lint for `x.get(...).unwrap(...)`

### ISSUE THREAD

**Issue by casey** [Manishearth/rust-clippy#1310]
I was doing stuff with maps and I didn't know that they supported access with `[]`, so I wrote  a lot of expressions like the following:

```
let map = std::collections::HashMap::new();

...

let key = "hello";

if map.contains_key(key) {
  let value = map.get(key).unwrap();
}
```

I think suggesting `map[key]` instead of `map.get(key).unwrap()` would be a good lint.

I know that I could have used an `if let Some(value) = map.get(key) ...` to extract the value, but because of lexical borrows I wasn't able to do so.

**Comment by casey** [comment]
PS: I love me some clippy! I ran it on a project I've been working on, and it suggested a ton of nice improvements.

**Comment by devonhollowood** [comment]
I'll give this a shot.

**Comment by casey** [comment]
Awesome!
