### ISSUE TITLE
0.0.96 does not compile on the latest nightly

### ISSUE THREAD

**Issue by mcarton** [Manishearth/rust-clippy#1320]
See https://travis-ci.org/Manishearth/rust-clippy/builds/169746235.

Looks like *clippy v0.0.96* does not compile on *rustc 1.14.0-nightly (7c69b0d5a 2016-11-01)*.
I just moved in and don't have a real Internet access (or a bed) yet, so I won't be able to fix this one.

**Comment by k4rtik** [comment]
Same behavior for `nightly-x86_64-unknown-linux-gnu updated - rustc 1.14.0-nightly (5665bdf3e 2016-11-02)`

My workaround is to use nightly-2016-10-27 for now.

**Comment by oli-obk** [comment]
published 0.97, sorry for taking so long
