### ISSUE TITLE
does not compile with rustc 1.15.0-nightly (1c448574b 2016-11-28)

### ISSUE THREAD

**Issue by durka** [Manishearth/rust-clippy#1371]
A ton of stuff seems to have been renamed. Errors can be seen here: https://travis-ci.org/durka/guard/jobs/180149918#L253

**Comment by oli-obk** [comment]
on it

**Comment by oli-obk** [comment]
this is not a fun one... I'm compiling already, but getting crashes in rustc and clippy when testing...

**Comment by nordlow** [comment]
Does it compile with 1.13 or 1.14?

**Comment by mcarton** [comment]
It compiles with rustc *1.15.0-nightly (2217bd771 2016-11-25)*.

**Comment by nbigaouette** [comment]
I was able to compile/install clippy yesterday using a nightly from November 25th. That's the last one that worked for me.

```
rustup toolchain install nightly-2016-11-25
rustup run nightly-2016-11-25 cargo install clippy
rustup run nightly-2016-11-25 cargo clippy
```

**Comment by nordlow** [comment]
Should I start with

```shell
curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly
```

?

**Comment by nbigaouette** [comment]
@nordlow use https://rustup.rs/ instead. Not yet official, but close!

**Comment by nordlow** [comment]
Ok, I'm trying it out now. I chose nightly. Ok?

**Comment by nbigaouette** [comment]
Just follow the instruction from the site to install it (it's going to ask you questions, can't remember which ones though).

Once rustup is installed, just run the three commands I've posted:
```
rustup toolchain install nightly-2016-11-25
rustup run nightly-2016-11-25 cargo install clippy
rustup run nightly-2016-11-25 cargo clippy
```

This will install clippy using the nightly from November 25th, and run it on your code base.

You can always install a "latest" nightly, beta or stable. Refer to https://github.com/rust-lang-nursery/rustup.rs for more info.

**Comment by nordlow** [comment]
What does `cargo clippy` do?

**Comment by brunoqc** [comment]
> What does cargo clippy do?

It runs clippy on the current project.

**Comment by nbigaouette** [comment]
Clippy [can be run multiple ways](https://github.com/Manishearth/rust-clippy#usage). One of those is through a "cargo-clippy" binary, which [was installed](https://github.com/Manishearth/rust-clippy#as-a-cargo-subcommand-cargo-clippy) using `cargo install clippy`.

I basically runs clippy on your files, without having to annotate the source files or add clippy to your Cargo.toml.

**Comment by nordlow** [comment]
I could run it as

```shell
rustup run nightly-2016-11-25 cargo build
```

aswell!

I guess this runs it as a rustc plugin, right?

This so cool!

**Comment by nbigaouette** [comment]
yes ;)

**Comment by nordlow** [comment]
My cargo bash completion has stopped working. It previously was placed in `/usr/local/etc/bash_completion.d/cargo`. I cant find anymore.

**Comment by lfairy** [comment]
@nordlow If you'd like help using Rust or Cargo, I suggest asking on the [users' forum](https://users.rust-lang.org/c/help) instead.

**Comment by nordlow** [comment]
Ok, thanks,
