### ISSUE TITLE
Fails to compile on latest Nightly

### ISSUE THREAD

**Issue by Ploppz** [Manishearth/rust-clippy#1382]
I updated to latest nightly with `rustup update`. The version is `rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)`.

Compiler errors: https://bpaste.net/show/36306aeb3de7

**Comment by oli-obk** [comment]
This is known. We must wait until rust publishes another nightly, because the latest published nightly made it impossible for clippy to work with. The fix is #1373
