### ISSUE TITLE
Lint for enums with no variants

### ISSUE THREAD

**Issue by clarcharr** [Manishearth/rust-clippy#1383]
Because the `!` type is now implemented on nightly, it would be nice to have a lint that would warn on enums with no variants, suggesting to use `!` instead. We could wait until the feature is stable to enable it by default.

**Comment by llogiq** [comment]
I disagree with this – this would have triggered on most of [typenum](https://github.com/paholg/typenum), (until we changed the types to become inhabited recently) for example. Not all uninhabited types are created equal.

**Comment by clarcharr** [comment]
@llogiq That's fair, and that leaves two options: 1) disable it by default or 2) encourage wrapper structs, i.e. `struct Wrap(!)`. I feel like the former might be a better option, although I also feel that in most cases creating an enum without any variants is a programmer mistake.

**Comment by llogiq** [comment]
We always have room for `allow` by default lints. And perhaps in the future, we may come to embrace the belief that empty `enum`s are wrong and uninhabited types should simply wrap `!`, at which point we can set the lint to `warn` by default.
