### ISSUE TITLE
--message-format argument doesn't shown in clippy --help

### ISSUE THREAD

**Issue by KalitaAlexey** [Manishearth/rust-clippy#1403]
Hi everybody.

Latest clippy doesn't show that it supports `--message-format`, but it does support it.

**Comment by mcarton** [comment]
It does say

> Other options are the same as `cargo rustc`.”

I didn't want to copy `cargo rustc`'s `--help` because most flags are not that useful and I didn't want to have to keep it synced. `--message-format` is one of those flags that are nice to have when writing specific tools, but not really useful for someone seeking general help.

**Comment by KalitaAlexey** [comment]
@mcarton,
I didn't see this. Thank you.
