### ISSUE TITLE
carg

### ISSUE THREAD

**Issue by gttiankai** [Manishearth/rust-clippy#1416]
Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling quine-mc_cluskey v0.2.4
   Compiling matches v0.1.4
   Compiling rustc-serialize v0.3.22
   Compiling nom v1.2.4
   Compiling regex-syntax v0.3.9
   Compiling unicode-normalization v0.1.3
   Compiling semver v0.2.3
   Compiling toml v0.1.30
   Compiling clippy_lints v0.0.104
error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:3:1
  |
3 | #![feature(box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:4:1
  |
4 | #![feature(collections)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:5:1
  |
5 | #![feature(custom_attribute)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:6:1
  |
6 | #![feature(rustc_private)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:7:1
  |
7 | #![feature(slice_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:8:1
  |
8 | #![feature(stmt_expr_attributes)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/tiankai/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.104/src/lib.rs:9:1
  |
9 | #![feature(repeat_str)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 7 previous errors

error: failed to compile `clippy v0.0.104`, intermediate artifacts can be found at `/var/folders/pk/4y7h8l3s7tj7glcjrkq_ggw80000gn/T/cargo-install.EKiEJ9qlb6BG`

Caused by:
  Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.

**Comment by mcarton** [comment]
See #1417.
