### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by luyang177** [Manishearth/rust-clippy#1426]
After 'rustup update'

C:\Users\admin>cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling nom v1.2.4
   Compiling rustc-serialize v0.3.22
   Compiling matches v0.1.4
   Compiling regex-syntax v0.3.9
   Compiling unicode-normalization v0.1.3
   Compiling semver v0.2.3
   Compiling quine-mc_cluskey v0.2.4
   Compiling toml v0.1.30
   Compiling clippy_lints v0.0.106
error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:3:1
  |
3 | #![feature(box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:4:1
  |
4 | #![feature(collections)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:5:1
  |
5 | #![feature(custom_attribute)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:6:1
  |
6 | #![feature(i128_type)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:7:1
  |
7 | #![feature(rustc_private)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:8:1
  |
8 | #![feature(slice_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:9:1
  |
9 | #![feature(stmt_expr_attributes)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
  --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:10:1
   |
10 | #![feature(repeat_str)]
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
  --> .cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.106\src\lib.rs:11:1
   |
11 | #![feature(conservative_impl_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 9 previous errors

error: failed to compile `clippy v0.0.106`, intermediate artifacts can be found at `C:\Users\admin\AppData\Local\Temp\cargo-install.vrdbyIalXjvu`

Caused by:
  Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.

**Comment by Manishearth** [comment]
Please see the readme. Clippy only works on nightly.

**Comment by llogiq** [comment]
As the README.md lays out, you'll need to build clippy with a nightly Rust.

Since it's known and documented, I'm closing this issue. If you disagree, please reopen and tell us why.

**Comment by luyang177** [comment]
yes, I work with nightly Rust.
As you see
C:\Users\admin>rustup run nightly rustc --version
rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)

**Comment by Manishearth** [comment]
`cargo install` will use the default toolchain. Your command only demonstrates that the nightly toolchain is _installed_. Try `cargo +nightly install`

**Comment by Manishearth** [comment]
(Also, cargo clippy will only work on projects when you have set the toolchain to nightly)

**Comment by luyang177** [comment]
Thank you very much.
I forget run 'rustup default nightly'
