### ISSUE TITLE
lint naive counts

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#1446]
Lint `_.iter().filter(predicate).count()`, suggest `_.iter().map(|x| predicate(x) as usize).sum()`, which results in branchless code that is usually faster.

**Comment by mcarton** [comment]
Meh, the semantic of `filter().count()` is clearer, if `.map(as usize).sum()` really is more efficient, this is to be fixed in *rustc*.

**Comment by llogiq** [comment]
I agree. Leaving this open until fixed.

**Comment by llogiq** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/39107
