### ISSUE TITLE
`clippy.toml` is undocumented

### ISSUE THREAD

**Issue by FaultyRAM** [Manishearth/rust-clippy#1455]
I noticed that the wiki no longer documents `clippy.toml` options, and I don't see them documented anywhere else. Was that intentional?

**Comment by mcarton** [comment]
I still see them, [example:](https://github.com/Manishearth/rust-clippy/wiki#cyclomatic_complexity)

> **Configuration**: This lint has the following configuration variables:
>
> * `cyclomatic-complexity-threshold: u64`: The maximum cyclomatic complexity a function can have (defaults to `25`).

Do you have a specific example of non-documented variable?

**Comment by FaultyRAM** [comment]
`doc-valid-idents` in particular disappeared in [this](https://github.com/Manishearth/rust-clippy/wiki/Home/_compare/50829fb768d8a7121c7a9c282c1c96544eceed23...d50ab1121c621e9aba6f0723238adba8b4aa6aa6#diff-b4d7124d2993cd13aabeec1fc19baf51L868) commit. Not sure if there were any others.

**Comment by mcarton** [comment]
Indeed, that's because of rustfmt. Fixing.
