### ISSUE TITLE
Help message: "This is not JavaScript" when using `===`.

### ISSUE THREAD

**Issue by Havvy** [Manishearth/rust-clippy#148]
Some of us are so used to using `===` for equality that we do so even in languages that don't have it by accident. A help message telling us this isn't JavaScript would help save a couple seconds of derp when it happens.

Though if this is out of scope of rust-clippy, that's okay too.

**Comment by birkenfeld** [comment]
I don't think this would be valid syntax, so it will throw an error long before the linting stage is reached.

**Comment by llogiq** [comment]
[Yep](https://play.rust-lang.org/?gist=c0d7588b4c5a981a7649&version=stable). I also think the given message "unexpected token: '='" with a caret indicating the position on the third '`=`' is sufficiently telling.

I'm closing this.
