### ISSUE TITLE
Lint fns that take immutable refs and return mutables

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#1507]
The recent 1.15.0 release had an error where a newly stabilized API function returned a mutable ref from `&self`. We should lint such functions (and probably allow them around `UnsafeCell`).

**Comment by oli-obk** [comment]
can you link to that function?

**Comment by llogiq** [comment]
https://github.com/rust-lang/rust/issues/39465 has the goods

**Comment by Manishearth** [comment]
Even unsafecell doesn't do this, it returns mutable raw pointers. And cell/refcell do their own thing.

It's basically very rarely a good idea.

**Comment by llogiq** [comment]
Even better to lint against it.
