### ISSUE TITLE
ty::TyTuple fields mismatch

### ISSUE THREAD

**Issue by leonardo-m** [Manishearth/rust-clippy#1519]
Trying to compile `clippy v0.0.113` on the latest nightly, nightly-x86_64-pc-windows-gnu (default), rustc 1.17.0-nightly (c49d10207 2017-02-07), the compilation of Clippy gives:

    error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
       --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.113\src\derive.rs:161:29
        |
    161 |                             TypeVariants::TyTuple(tys) if tys.len() > 12 => {
        |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

       Compiling serde_derive v0.9.6
    error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
       --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.113\src\types.rs:200:13
        |
    200 |             ty::TyTuple(slice) if slice.is_empty() => {
        |             ^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

    error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
       --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\clippy_lints-0.0.113\src\types.rs:271:21
        |
    271 |                     ty::TyTuple(slice) if slice.is_empty() => {
        |                     ^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

    error: aborting due to 3 previous errors

    error: Could not compile `clippy_lints`.
    Build failed, waiting for other jobs to finish...
    error: failed to compile `clippy v0.0.113`, intermediate artifacts can be found at `...\AppData\Local\Temp\cargo-install.mCSHo22OEP9E`

**Comment by oli-obk** [comment]
easy rustup :) will publish in a few minutes.

**Comment by oli-obk** [comment]
scratch that. rustup easy, compiletest horrible. We have around 50 million new `NOTE` that we can't ignore. I'll move us to ui-tests, this is impossible.
