### ISSUE TITLE
`or_fun_call` should ignore `const fn`s

### ISSUE THREAD

**Issue by sgrif** [Manishearth/rust-clippy#1527]
Hi there. I was surprised to find that clippy warns on `foo.map(CStr::as_ptr).unwrap_or(ptr::null_mut())`. Given that `null_mut` is a `const fn`, forcing it to be in `unwrap_or_else(|| ptr::null_mut())` is just noise. (I'm also unsure whether enum constructors are technically `const fn`s, but fixing this could potentially fix #1338)

**Comment by mcarton** [comment]
I cannot reproduce even in diesel's repo and this should have been fixed in #917. The original PR on diesel is older than #917, this might have been the problem.
I can however reproduce #1338.
Feel free to reopen if you have a reproducible example.

**Comment by killercup** [comment]
> The original PR on diesel is older than #917, this might have been the problem.

Can confirm. I'm pretty good at cargo culting changes like that without thinking about it 😄
