### ISSUE TITLE
Port the proposed python script (that updates README/lib.rs) to build script

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#153]
If we port this to a build script, we can have Cargo automatically update the files on compile – no more forgetting to run python.

Yes, it's a nice-to-have, but pretty cool. I even imagine it shouldn't be too hard.

**Comment by birkenfeld** [comment]
This occurred to me as well, but I'm not a fan of the build process potentially changing checked-in files.

What we could also do is to let Travis run the script, and error out if one of the files changed.

**Comment by Manishearth** [comment]
I agree with @birkenfeld here, build scripts should not change checked-in things.

**Comment by llogiq** [comment]
OK, so we'd manually need to run the script, to keep travis from throwing an error on us.

Closing this issue.

**Comment by Manishearth** [comment]
We can make Travis run the script as part of the test routine, though. Something like

`python script.py && [ $(git diff) -e  ] || echo "Please run script.py and commit the changes" && exit 1`

**Comment by birkenfeld** [comment]
Already on it...
