### ISSUE TITLE
`len_without_is_empty` requires `allow` in the wrong place.

### ISSUE THREAD

**Issue by sgrif** [Manishearth/rust-clippy#1532]
When a struct fails the `len_without_is_empty` lint, the error span shows the definition of the `len` method. However, adding `#[allow(len_without_is_empty)]` on the method does nothing. Clippy wants it on the struct itself. I'd expect that the place to add `#[allow]` is always on the span shown in the error.

**Comment by theotherphil** [comment]
I'm new to clippy, but I'd like to give this a go.

**Comment by mcarton** [comment]
@theotherphil Great! Don't hesitate to open a PR even if it's not finished or to ask questions if you have any problem!
