### ISSUE TITLE
Promote unwrap_or_default

### ISSUE THREAD

**Issue by nox** [Manishearth/rust-clippy#1533]
Calls such as `option.unwrap_or(Default::default())` or `option.unwrap_or_else(Default::default)` are better written as `option.unwrap_or_default()`.

**Comment by clarcharr** [comment]
Don't forget `Result::unwrap_or_default` too.

**Comment by leodasvacas** [comment]
I thought this already existed as part of #556

**Comment by nox** [comment]
Oh.
