### ISSUE TITLE
calls to `std::mem::drop` with a `Copy` type

### ISSUE THREAD

**Issue by F001** [Manishearth/rust-clippy#1537]
If `x` is `Copy`, `std::mem::drop(x)` has no effect on this variable. This statement is redundant.

This can be an extension of `drop_ref` rule.

**Comment by clarcharr** [comment]
This should also apply to `mem::forget`.

**Comment by tristianc** [comment]
I'd like to take this.

**Comment by mcarton** [comment]
@tristianc Great! Don't hesitate to open a PR even if it's not finished or to ask questions if you have any problem!

**Comment by oli-obk** [comment]
This has been fixed in #1575
