### ISSUE TITLE
Suggest `b"foo"` when one writes `"foo".as_bytes()`

### ISSUE THREAD

**Issue by frewsxcv** [Manishearth/rust-clippy#1546]

**Comment by frewsxcv** [comment]
Actually it looks like https://github.com/Manishearth/rust-clippy/wiki#string_lit_as_bytes exists, but I didn't get a warning here: https://github.com/azerupi/mdBook/pull/205/files#diff-19752743a4acf5322ab48ce94ca4a1f0R43

**Comment by sinkuu** [comment]
`string_lit_as_bytes` lint (and many other, too) skips macros. (You should get warnings if you use `?` operator instead of `try`.)

**Comment by frewsxcv** [comment]
Ah cool, thanks @sinkuu
