### ISSUE TITLE
travis compiles twice

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#156]
I noticed that because it has `cargo build` and `cargo test` in the commands list, the travis build does two full compiles. Is that necessary, or will the compile for `cargo test` already find anything that `cargo build` would?

**Comment by Manishearth** [comment]
`cargo test` compiles with `--cfg test`, so any inline unit tests will get run too

**Comment by Manishearth** [comment]
We could just run `cargo test`, shouldn't cause any problems

**Comment by llogiq** [comment]
Agreed, this would speed up travis. I guess the standard build&&test sequence is common because some crates use `#[cfg(test)]` *and* `#[cfg(not(test))]` for swapping out test-related functionality.

**Comment by birkenfeld** [comment]
Nice!
