### ISSUE TITLE
Explicit use of a.iter()/a.iter_mut() instead of &a/&mut a

### ISSUE THREAD

**Issue by jdm** [Manishearth/rust-clippy#157]
When all you're doing is iterating over a slice of something, you might as well use the nicer syntax for it.

**Comment by Manishearth** [comment]
This might need to use [`recover_for_loop`](https://github.com/Manishearth/rust-clippy/blob/master/src/loops.rs#L52) to resugar a for loop, but otherwise is a pretty straightforward matching of an `ExprMethodCall` in the iterator argument of a for loop.
