### ISSUE TITLE
clippy_lints fails to compile with 93 errors.

### ISSUE THREAD

**Issue by iitalics** [Manishearth/rust-clippy#1591]
Hello, I've recently tried building another project ([ralloc](https://github.com/redox-os/ralloc)), which depends on `clippy_lint`. However I'm getting nearly a hundred errors

```
$ cargo build
   Compiling clippy_lints v0.0.85
error[E0432]: unresolved import `syntax::parse::token::InternedString`
 --> /home/milo/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.85/src/utils/internal_lints.rs:3:5
  |
3 | use syntax::parse::token::InternedString;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `InternedString` in `parse::token`

...

error[E0106]: missing lifetime specifiers
  --> /home/milo/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.85/src/zero_div_zero.rs:30:6
   |
30 | impl LateLintPass for Pass {
   |      ^^^^^^^^^^^^ expected 2 lifetime parameters

error: aborting due to 93 previous errors

error: Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.
```

I'm on the beta channel, since ralloc won't compile on stable. This is also the case in nightly.

**Comment by oli-obk** [comment]
[Clippy only works on nightly](https://github.com/Manishearth/rust-clippy#usage) Please use the nightly compiler.

**Comment by oli-obk** [comment]
Note that for ralloc, you can disable clippy, since it's just an optional feature.

**Comment by iitalics** [comment]
```
$ rustc --version
rustc 1.17.0-nightly (c0b7112ba 2017-03-02)
```

Looks like I'll be disabling clippy then...

**Comment by oli-obk** [comment]
ralloc is depending on a really old version of clippy, I'm opening a PR there to remove that dependency.

**Comment by iitalics** [comment]
Thank you
