### ISSUE TITLE
Creating a String / Vec for comparison

### ISSUE THREAD

**Issue by kmcallister** [Manishearth/rust-clippy#16]
```rust
x == String::from_str("foo")
```

should be

```rust
x.as_slice() == "foo"
```

to avoid the allocation.

**Comment by llogiq** [comment]
The lint in #63 matches on `String::from_str(_)`, `_.to_string()` and `_.to_owned()`. Is there anything else we should match?

**Comment by llogiq** [comment]
Ok, it appears that we have the most common cases in #65. @kmcallister If I missed a case that you want checked, please reopen. :smile:
