### ISSUE TITLE
Collapsible-if shouldn't error if ifs are generated by macros

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#161]
It seems like we do check for macros, but perhaps it isn't enough?

https://github.com/Manishearth/rust-clippy/blob/master/src/collapsible_if.rs#L45

`in_macro` tests for external macros, but internal macros can be problematic for this lint too.

I thought we could check if the `ExpnId`s of the two `Span`s of each `if` match, but this doesn't seem to work. 

cc @birkenfeld

**Comment by birkenfeld** [comment]
I'm guessing internal macros are excluded because you could theoretically fix them? Otherwise I don't see a reason to distinguish between internal and external...

**Comment by Manishearth** [comment]
For most lints, yes, but in this case each if comes from a different invocation of the same macro, so that can't be fixed.

**Comment by llogiq** [comment]
That explanation needs an explanation.

**Comment by birkenfeld** [comment]
Well, it can be fixed by rewriting the macro arguments.

**Comment by Manishearth** [comment]
Oh, I see what you mean. Yeah, technically this isn't a false positive then.


Still think we need better macro handling since fixing macros isn't always an option, but we can keep the lint this way until we hit other such cases.
