### ISSUE TITLE
`needless_pass_by_value` should ignore `#[proc_macro_derive]` functions. 

### ISSUE THREAD

**Issue by sgrif** [Manishearth/rust-clippy#1615]
Functions marked with `#[proc_macro_derive]` must have the exact signature `(TokenStream) -> TokenStream`. There are no methods on `TokenStream` which require ownership, so any proc macro crate which uses clippy will trigger this lint by default, even though the recommended solution cannot be taken.

**Comment by dtolnay** [comment]
We need this for `#[proc_macro]` and `#[proc_macro_attribute]` as well. I filed #3067 to follow up.
