### ISSUE TITLE
Elision lint should bail if we're using named lifetimes defined *outside* the function

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#162]
This is for methods which use named lifetimes which are defined elsewhere (not in `fn foo<'a, 'b>(..`), e.g. https://github.com/Manishearth/rust-clippy/blob/master/src/loops.rs#L106

I think when we encounter such lifetimes we can only bail, because the lifetime may or may not be connected with the self type and elision can't do much anyway.

cc @birkenfeld

**Comment by Manishearth** [comment]
We can jsut check here that the input and output hashsets don't contain anything other than `'static` and lifetimes named in the FnDecl

**Comment by birkenfeld** [comment]
Good point. Sounds easy enough...

**Comment by Manishearth** [comment]
http://manishearth.github.io/rust-internals-docs/syntax/visit/enum.FnKind.html, get the lifetimes from the `Generics` in `FkItemFn` or `MethodSig`, and just compare the vecs for anything extra

**Comment by Manishearth** [comment]
(I've got it half-working already, just posting what I have since you seem to want to do it :smile: )

**Comment by Manishearth** [comment]
We also should bail if any of the named lifetimes are bounded
