### ISSUE TITLE
running clippy against libcore panics

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#1623]
The problem is in `needless_pass_by_value` trying to get the `AsRef` trait, which is not available yet. Changing the code to warn instead of panic makes it work.

**Comment by oli-obk** [comment]
I wonder how we can test for such no_std issues in general. Maybe we should simply bail on all failed queries to the compiler?

**Comment by llogiq** [comment]
I'd at least log an error so people won't be surprised.

**Comment by oli-obk** [comment]
Surprised? That the lint doesn't trigger? It should not trigger if not applicable. So if a trait isn't available due to no_std, then we should not be doing any suggestions related to that.

**Comment by llogiq** [comment]
True. Still, for the general case, I'd like an `expect!` macro that emits the given message and `return`s.
