### ISSUE TITLE
float_cmp should be okay when comparing with zero

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#165]
`== 0` or `0 == ` are okay, but other numbers have a chance of imprecision.

**Comment by birkenfeld** [comment]
:+1:

**Comment by terrynsun** [comment]
I can take a look at this one? :)

**Comment by terrynsun** [comment]
Are you working on this or just endorsing it? (I'd like to try it if you aren't.)

**Comment by llogiq** [comment]
I think it's just an endorsement. He would have been finished by now had he decided to work on it. :smile:

**Comment by birkenfeld** [comment]
:smile: go ahead! @llogiq this may be good to base on the constant folding branch?

**Comment by llogiq** [comment]
It would certainly be helpful. I shall add a `.as_float(&self) -> Option<f64>` function to `Constant`.

**Comment by Manishearth** [comment]
@terrynsun go ahead! don't worry about constant folding for now -- we should do that once that branch lands
