### ISSUE TITLE
Document a nightly version that compiles a new clippy release

### ISSUE THREAD

**Issue by johnthagen** [Manishearth/rust-clippy#1651]
Would it be possible to document one nightly version that is known to work for a particular clippy release? Since clippy versions are generally bound to some slice of nightly rustc versions, what I do is [statically set](https://github.com/johnthagen/rust-belt/blob/master/.travis.yml#L27-L28) these in the Travis configuration. About once a month, I then try the latest nightly and clippy versions together to see if I can bump them together to get bug fixes and updates to clippy.

The issue is that often when I check I seem to hit the period when clippy doesn't work with the latest nightly rustc. At this point, I could start doing a binary search backward in time to find a version of nightly that works. If this was documented, it would save a lot of time and make updating to newer versions of clippy much easier.

**Comment by Manishearth** [comment]
We're working on making it possible to use clippy on stable, so not really trying to fix the nightly problems now.

**Comment by johnthagen** [comment]
@Manishearth Sounds great. Feel free to close this issue.

**Comment by kdar** [comment]
In case anyone comes across this before clippy is integrated into rustup. Go here: https://travis-ci.org/rust-lang-nursery/rust-clippy/branches, find the latest successful build for master (e.g. https://travis-ci.org/rust-lang-nursery/rust-clippy/builds/373722889), take note of the rustc version and clippy commit, and install them appropriately. It does seem you need to add 1 day to the rust version.

```bash
rustup install nightly-2018-04-30
rustup default nightly-2018-04-30-x86_64-unknown-linux-gnu
cargo install --force --git=https://github.com/rust-lang-nursery/rust-clippy --rev="77de1000d7ecb2419bf3402905c926bbcd588aba" clippy
```
