### ISSUE TITLE
Usage instructions for command line without installing do not work

### ISSUE THREAD

**Issue by shahn** [Manishearth/rust-clippy#1701]
I want to use a locally built clippy to lint a project. Here's what I did:
I cloned rust-clippy, built it using cargo build --release. It produces a target/release/libclippy.so as expected.

In my other project, I'm invoking

    cargo rustc -- -L <path/to/libclippy.so> -Z extra-plugins=clippy

Which gives:

    error[E0463]: can't find crate for `clippy`

**Comment by oli-obk** [comment]
Works fine on my end. The path after `-L` must be the folder, so `clippy/target/release`, not the full path to the .so file.

**Comment by shahn** [comment]
Of course you're right.
