### ISSUE TITLE
Compilation breakage: rustc_errors::CodeSuggestion

### ISSUE THREAD

**Issue by ishitatsuyuki** [Manishearth/rust-clippy#1714]
☔️ The latest upstream changes (presumably rust-lang/rust#40851) have made clippy unbuildable.

```
error[E0063]: missing field `msg` in initializer of `rustc_errors::CodeSuggestion`
   --> clippy_lints/src/utils/mod.rs:596:53
    |
596 |     let sugg = rustc_errors::RenderSpan::Suggestion(rustc_errors::CodeSuggestion {
    | 
```

@oli-obk wait, you made this one? probably you know what's the right way to port?

**Comment by oli-obk** [comment]
jup, thanks for the report! I'll fix it asap

**Comment by oli-obk** [comment]
It'll probably appear in tomorrows nightly, so we're not merging until tomorrow.
