### ISSUE TITLE
Clippy 0.0.131 fails to compile with nightly 2017-05-04

### ISSUE THREAD

**Issue by sztosz** [Manishearth/rust-clippy#1727]
Clippy 0.0.131 fails to compile with nightly 2017-05-04.
Nightly 2017-05-05 is broken and can't be installed https://github.com/rust-lang-nursery/rustup.rs/issues/1092
I also tried with clippy straight from the master branch
```
[dependencies]
clippy = {git = "https://github.com/Manishearth/rust-clippy", optional = true}
```
It fails with that error:
```
error[E0107]: wrong number of lifetime parameters: expected 0, found 1
   --> /Users/bartosz/.cargo/git/checkouts/rust-clippy-eb94f5e90699ab2d/3b03891/clippy_lints/src/loops.rs:878:35
    |
878 |     indexed: HashMap<Name, Option<CodeExtent<'tcx>>>, // indexed variables, the extent is None for global
    |                                   ^^^^^^^^^^^^^^^^ unexpected lifetime parameter
```

I'm a real newbie to Rust, so I'm not sure what to try more other than report it.

**Comment by oli-obk** [comment]
thx, I'm already on it

**Comment by oli-obk** [comment]
hmm... it works with nightly-2017-05-04... I'm not sure what causes this... Can you try running `cargo update`?

**Comment by sztosz** [comment]
Damn... I learn more and more about rust almost every minute I'm doing with it anything. I installed nightly-2017-05-04 but my default was nightly from april, because if you install nightly with explicit date it does not overwrite current nightly. With nightly 2017-05-04 it works like a charm!

I'm sorry my lack of  knowledge took your valuable time, but at least it learned me something.

**Comment by oli-obk** [comment]
Great! always happy to help

**Comment by Arnavion** [comment]
This is actually happening now with `clippy v0.0.132` with `rustc 1.19.0-nightly (826d8f385 2017-05-13)` because of https://github.com/rust-lang/rust/commit/ea1c6df81eecad62ca25191042b7871291162933#diff-eaec58cd2e0c9e0564f2f3f7e417340cL38
