### ISSUE TITLE
cmp_owned suggests advice that can cause infinite recursion

### ISSUE THREAD

**Issue by SamWhited** [Manishearth/rust-clippy#1730]
The [`cmp_owned`](https://github.com/Manishearth/rust-clippy/wiki#cmp_owned) warning suggests using `self == other` instead of `self.to_owned() == other`:

> this creates an owned instance just for comparison. Consider using `self == other`
> …
>     self.to_string() == other

However, if the code that triggers this warning is in the `PartialEq` implementation itself, following the warnings advice now leads to a recursive call to `eq`.

**Comment by SamWhited** [comment]
> Uhm.... ihmo allocating in a cmp impl is not a good thing...

I agree, the specific implementation or whether or not it's a good idea is beside the point though, it was just an example. The point is that `self == other` is incorrect advice in this context (maybe if it's in a `PartialEq` implementation it could say something along the lines of "please try not to allocate in this context " instead of suggesting "self == other"?

**Comment by oli-obk** [comment]
This is included in the 0.0.132 release
