### ISSUE TITLE
Empty lines in tests

### ISSUE THREAD

**Issue by luisbg** [Manishearth/rust-clippy#1734]
When all //~ were removed from tests, these were replaced with empty
lines to leave the numbers in the expected stderr untouched.

These empty lines need to be cleaned for clarity.

Here is an example: #1733

**Comment by luisbg** [comment]
Can somebody with priviledges to do so can assign this to me?

Wanted to have an open issue so people know I am working on this :smile:

**Comment by Manishearth** [comment]
GitHub doesn't let you, but your comment should suffice

**Comment by Manishearth** [comment]
(GitHub only supports assigning to collaborators which sucks)

**Comment by mcarton** [comment]
@Manishearth it's also been supporting the OP for some time now \o/

**Comment by oli-obk** [comment]
Yay! no more C-assigned

**Comment by luisbg** [comment]
\o/

**Comment by luisbg** [comment]
\o/

Once the compiletest-rs issue is solved I will fix a bunch of these tests with empty lines.

**Comment by oli-obk** [comment]
We just need to wait until a nightly is published

**Comment by llogiq** [comment]
Good thing you're sorting the weird newlines out, @luisbg – and good to know that github now lets us assign issues to anyone, @mcarton :+1:

**Comment by mcarton** [comment]
I don't think it's anyone, just the owner and collaborators as before, plus the OP of the issue (eg. you can't assign @luisbg to #1709).

**Comment by luisbg** [comment]
This has been merged. The issue can be closed :smiley:
