### ISSUE TITLE
`let_and_return` ignores type inference

### ISSUE THREAD

**Issue by vks** [Manishearth/rust-clippy#1735]
`{ let x: T = ...; x }` generates a warning, but it is not possible to replace it with `{ ...: T }` on stable. (Type ascription is unstable.)

**Comment by oli-obk** [comment]
Bonus points if this message is only supressed if `T` differs from the return type of a function and the block is the body of the function.

**Comment by vks** [comment]
> Bonus points if this message is only supressed if T differs from the return type of a function and the block is the body of the function.

And if the function is not a closure and does not use `impl Trait`.
