### ISSUE TITLE
ICE on {:#p} when taking a pointer argument

### ISSUE THREAD

**Issue by Ekleog** [Manishearth/rust-clippy#1753]
With rustc-2017-05-05 and clippy-0.0.131, compiling the following file causes an ICE, while rustc alone is able to compile it without error:

```rust
pub fn foo(bar: *const u8) {
    println!("{:#p}", bar);
}
```

**Comment by oli-obk** [comment]
fixed in 29cb2f7 and released as 0.0.132

**Comment by Ekleog** [comment]
Thanks!
