### ISSUE TITLE
Wrong suggestion about debug_assert!()

### ISSUE THREAD

**Issue by RazrFalcon** [Manishearth/rust-clippy#1757]
The `#[warn(should_assert_eq)]` suggest to use `assert_eq`. But unlike `debug_assert` it will be checked in runtime too. This macros are not the same.

**Comment by llogiq** [comment]
So it should suggest `debug_assert_eq`, right?

**Comment by RazrFalcon** [comment]
Does it even exists? I don't know what it should suggest, but current suggestion is ambiguous.

**Comment by mcarton** [comment]
Yes [`debug_assert_eq`](https://doc.rust-lang.org/std/macro.debug_assert_eq.html) exists.

**Comment by RazrFalcon** [comment]
That's even better. That is should suggest `debug_assert_eq`.
