### ISSUE TITLE
Clippy won't build on latest nightly

### ISSUE THREAD

**Issue by MortenLohne** [Manishearth/rust-clippy#1769]
Installing clippy through `cargo install clippy` seems to be broken. It fails with:

    error: no method named `populate_implementations_for_trait_if_necessary` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
       --> /home/morten/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.133/src/utils/mod.rs:328:12
    328 |     cx.tcx.populate_implementations_for_trait_if_necessary(trait_id);

Using nightly-x86_64-unknown-linux-gnu - rustc 1.19.0-nightly (0ed1ec9f9 2017-05-18).

**Comment by oli-obk** [comment]
I'm still on mobile, I'll publish in around an hour

**Comment by oli-obk** [comment]
published 0.0.134
