### ISSUE TITLE
Activates on macros

### ISSUE THREAD

**Issue by legolord208** [Manishearth/rust-clippy#1771]
I have macros that return, such as `fail!("oh no some error")`, which returns a struct with default parameters and saying it's an error.

I need to use the `return` keyword, since I should be able to fail at any time, not *just* at the end of the function, but might be as well.

That's the problem. When I use one of these macros at the end of the function, Clippy tells me to go remove `return`. But hey clippy, that won't work.

**Comment by oli-obk** [comment]
just needs a macro check.

**Comment by clarcharr** [comment]
Perhaps a better title for this would be "needless_return should have a macro check"

**Comment by clarcharr** [comment]
Actually, this is a duplicate of #1271.

**Comment by legolord208** [comment]
Well, it's not only needless_return. Other warnings too

**Comment by oli-obk** [comment]
Closing as duplicate, please open a new issue for the other lints you encountered which need a macro check. Some lints don't have a macro check on purpose
