### ISSUE TITLE
map_entry lint (contains_key followed by insert) too eager with custom already-exists logic

### ISSUE THREAD

**Issue by radix** [Manishearth/rust-clippy#1774]
I have several instances of the following pattern in my codebase:

```rust
if map.contains_key(key) {
    bail!("Already contains key!");
} else {
    map.insert(key, value);
}
```

Clippy matches this code with the `map_entry` lint, which suggests I use `map.entry(key)`, but I don't *think* that helps in this situation; the HashMap Entry API doesn't have anything for "insert this key but just return this other value, without modifying the map, if it already exists".

**Comment by mcarton** [comment]
What is wrong with

```rust
if let Vacant(v) = map.entry(key) {
    v.insert(value);
} else {
    bail!("Already contains key!");
}
```
?

**Comment by radix** [comment]
I had no idea that Entry had public variants!

However, the version you suggested is slightly longer. Is there some reason other than brevity that it's better to use that instead of contains_key / insert?

**Comment by mcarton** [comment]
Yup, see [`Entry`'s documentation](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html).

102 vs. 104 characters, I wouldn't say it's significantly longer.
More over the entry API is better as it only requires one lookup in the map, while the `contains_key` + `insert` needs two.

Feel free to reopen if you want to bring something more to the conversation, but for now, I'll close this issue.
