### ISSUE TITLE
Detecting #[no_std] compatibility

### ISSUE THREAD

**Issue by cbreeden** [Manishearth/rust-clippy#1779]
I don't know how feasible such a list would be, or how accurate it would be, but it might be nice to have a lint which detects no std compatibility.  This could increase the number of #[no_std] crates in the ecosystem.

cc @susurrus

**Comment by clarcharr** [comment]
Duplicate of #1569.

**Comment by cbreeden** [comment]
Appreciate it.  My GitHub searching skills failed me once again.
