### ISSUE TITLE
Compilation error on rustc 1.19.0-dev (4f9c9ed1a5 2017-05-27)

### ISSUE THREAD

**Issue by ishitatsuyuki** [Manishearth/rust-clippy#1785]
☔ The latest upstream changes (presumably https://github.com/rust-lang/rust/pull/40847) broke the build. Please fix the following errors.

```
error: no field `name` on type `&rustc::hir::def::Export`
   --> clippy_lints/src/utils/mod.rs:291:25
    |
291 |                 if item.name == *segment {  
    |                         ^^^^
error: aborting due to previous error(s)
error: Could not compile `clippy_lints`.
```

**Comment by mcarton** [comment]
Fixed in #1787.

**Comment by nateozem** [comment]
Note to anyone else that are having similar problems, it's resolved with the
latest `rustc` version on `nightly`.

	$ cargo clean && cargo build
	   .....
	   Compiling clippy_lints v0.0.136 
	error: no field `ident` on type `&rustc::hir::def::Export`
	   --> clippy_lints/src/utils/mod.rs:291:25
		|
	291 |                 if item.ident.name == *segment {
		|                         ^^^^^

	error: no method named `param_env` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
	   --> clippy_lints/src/utils/mod.rs:790:32
		|
	790 |     let parameter_env = cx.tcx.param_env(parameter_item);
		|                                ^^^^^^^^^

	error: no method named `param_env` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
	   --> clippy_lints/src/utils/mod.rs:810:22
		|
	810 |     let env = cx.tcx.param_env(env);
		|                      ^^^^^^^^^

	error: no method named `param_env` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
	  --> clippy_lints/src/needless_pass_by_value.rs:85:40
	   |
	85 |             let parameter_env = cx.tcx.param_env(fn_def_id);
	   |                                        ^^^^^^^^^

	$ rustc -vV
	rustc 1.19.0-nightly (01951a61a 2017-05-20)
	binary: rustc
	commit-hash: 01951a61a49dca35747dc9ba03e5536f337de239
	commit-date: 2017-05-20
	host: x86_64-apple-darwin
	release: 1.19.0-nightly
	LLVM version: 4.0

This can be fix by updating `nightly` version and the errors will be gone.

	$ rustup update
	....

	$ rustc -vV
	rustc 1.19.0-nightly (557967766 2017-05-26)
	binary: rustc
	commit-hash: 557967766be6139bd747ab2c3dc56ff0c9b8852a
	commit-date: 2017-05-26
	host: x86_64-apple-darwin
	release: 1.19.0-nightly
	LLVM version: 4.0

try it again and should work:

	$ cargo clean && cargo build
	   ..........
	   Compiling clippy_lints v0.0.136 
	   Compiling cargo_metadata v0.2.1
	   Compiling clippy v0.0.136 
		Finished dev [unoptimized + debuginfo] target(s) in 54.93 secs

**Comment by ishitatsuyuki** [comment]
Sigh, whoever would try to install latest clippy on outdated nightly? Please do not create a redundant notification for me, thanks.

**Comment by Manishearth** [comment]
Please be nice.

Not everyone knows how nightlies and clippy work.  It's quite likely that the commenter didn't and hit this problem. It's fine for them to clarify in case someone else does.

Disparaging comments like yours are not how we do things in this community.

If you don't like the notifications, unsubscribe from this thread.

**Comment by nateozem** [comment]
Appreciated @Manishearth.

I do wonder if anyone brought up the idea of notifying the developer to update `rustc` when it becomes obsolete at build time. 

I do see that  `CHANGELOG.md` file is updated (not before), but I don't see any other mechanism to let me know that the requirements has changed.  It's not my first thought when working on a project, is to update my build tools and probably for others too.

What do you think?

**Comment by Manishearth** [comment]
We're working towards packaging clippy with rustup so that this is all automatic. So we're not doing any stopgap measures.

The rule of thumb is that almost every clippy version bump comes with a rustup. If your clippy version is updated, update rustc too.

**Comment by nateozem** [comment]
Understand. Thanks for letting me know.
