### ISSUE TITLE
Add all as an alias, to allow -Wall

### ISSUE THREAD

**Issue by g2p** [Manishearth/rust-clippy#1812]
I would like to check my code for possible non-default clippy warnings, but adding them by hand is tedious. Please add a `-W all` alias to clippy invocations.

**Comment by Manishearth** [comment]
`-Wclippy` and `-Wclippy_pedantic` do this.

**Comment by llogiq** [comment]
Shouldn't -Wall be in `rustc` as a catch-all lint group?

**Comment by Manishearth** [comment]
There's -Wwarnings, but that's only for rustc builtins.

**Comment by mcarton** [comment]
`-Wall` does not mean all warnings anyway, everyone knows C and C++ must be compiled with `-Wall -Wextra -Wpedantic` 😅
