### ISSUE TITLE
Warn on "for x in iter.next()"

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#182]
... which will compile since Option is iterable.

From https://www.reddit.com/r/rust/comments/3h4u4v/take_advantage_of_iteration_syntax_to_act_on/cu4qqhc

**Comment by Manishearth** [comment]
Whoa, I can see that causing some devious bugs.

**Comment by Gankro** [comment]
Can confirm, wasted a good amount of time chasing false paths until I hit this -- an artifact of converting from a `while-let` to a `for`.

**Comment by devonhollowood** [comment]
I can do this.

**Comment by Manishearth** [comment]
@devonhollowood this was already fixed in https://github.com/Manishearth/rust-clippy/commit/e9a41e2374878d8537fab4f607f8f1c1401b0389 :smile:

**Comment by devonhollowood** [comment]
Whoops! I meant to comment on #584. I had them open in two separate tabs :flushed:
