### ISSUE TITLE
match_same_arms should not object when result of each arm is ()

### ISSUE THREAD

**Issue by mulkieran** [Manishearth/rust-clippy#1857]
In this particular case it is clear that side-effects are the purpose of the match, I think.

**Comment by oli-obk** [comment]
Match same arms only reports if the side effects are the same, too. Or am I misunderstanding something here?

**Comment by mulkieran** [comment]
No, I think in this case that an analysis could conclude that the actions are the same as well. Thanks for clearing that up.
