### ISSUE TITLE
Suggest `match *x { a => 0, b => 1 }` instead of `match x { &a => 0, &b => 1 }`

### ISSUE THREAD

**Issue by killercup** [Manishearth/rust-clippy#187]
What the title says. Instead of matching on the borrowed value and then prepending `&` to each match arm, you could also match on the deref'd value. (That's what it's called, right? It's Monday morning.)

This doesn't really change the semantics but shortens the code and makes it a bit clearer (IMHO). I'm not sure if it's really something _clippy_ wants to do (or rather something _rustfmt_ might offer), but I wanted to suggest it anyway.

Example:

```rust
enum Lit {Lorem, Ipsum, Dolor}

fn stuff(lit: &Lit) {
    match lit {
        &Lit::Lorem => println!("1"),
        &Lit::Ipsum => println!("2"),
        &Lit::Dolor => println!("3"),
    }
}

fn main() {
    stuff(&Lit::Lorem);
}
```

([Playpen](http://is.gd/nG6LB3)) can be written as

```rust
enum Lit {Lorem, Ipsum, Dolor}

fn stuff(lit: &Lit) {
    match *lit {
        Lit::Lorem => println!("1"),
        Lit::Ipsum => println!("2"),
        Lit::Dolor => println!("3"),
    }
}

fn main() {
    stuff(&Lit::Lorem);
}
```

([Playpen](http://is.gd/L6QSn1))

This of course only works when all match arms destructure the borrowed value anyway. This seems common enough, though. I just saw [this code](https://github.com/Manishearth/rust-clippy/blob/759b45a46d299f19a10477cc226e70002ac91340/src/consts.rs#L129-L142) in Manishearth/rust-clippy#184.

**Comment by Manishearth** [comment]
This seems like an acceptable lint to me.

**Comment by llogiq** [comment]
So if I had used `ref` in all match arms, the `&`s would have been correct.

Wouldn't it suffice if *one* match arm destructures the borrowed value? Also we could make a broader version of the lint that just checks if the matched value is `Copy`.
