### ISSUE TITLE
Fail to build with rustc 1.20.0-nightly (2fbba5bdb 2017-07-04)

### ISSUE THREAD

**Issue by uHOOCCOOHu** [Manishearth/rust-clippy#1872]
Here's the [detail log](https://gist.github.com/uHOOCCOOHu/dd0deb6de4d164939ee41fac5311201b).
Seems caused by rust-lang/rust#43012.

**Comment by oli-obk** [comment]
Just needs a rerun of cargo test + committing the changes

**Comment by uHOOCCOOHu** [comment]
@oli-obk Maybe I can do it. But I think codes using removed features in tests should be removed first, so that they will do the real "test".
