### ISSUE TITLE
Links to the wiki

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#210]
Now that the wiki has been started, we should link to it:

- [x] README.md – I'd have added it, but wouldn't want to mess up the table layout :smile:
- [ ] help- or note-messages in the respective lints?

@Manishearth Also should we add an L-documentation Label to our issues?

**Comment by llogiq** [comment]
Also hijacking my own issue; should we standardize the lint documentation on a certain format?

Perhaps:

* what it does
* why the linted code is bad/could be improved
* where it fails (known false negatives / positives)
* Examples

**Comment by Manishearth** [comment]
We should autogenerate the links, and yeah, there should be a help message (which first checks for the lint level). Probably should make a util function that takes a lint ident and outputs a standard help message.

**Comment by Manishearth** [comment]
(standardization sgtm)
