### ISSUE TITLE
Move const folding into rustc

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#213]
Rustc already does const folding (http://manishearth.github.io/rust-internals-docs/rustc/middle/const_eval/fn.eval_const_expr.html), though it can't handle ifs and whatnot.

We could improve the existing code in rustc with our additional features

cc @llogiq

**Comment by llogiq** [comment]
I'll be glad to improve rustc's const folding. Alas, it does not let us know if pats were resolved, so I'm not sure we can use it here.

**Comment by Manishearth** [comment]
We can figure out if something needed resolution by walking the expr for an exprpath

**Comment by llogiq** [comment]
Following the discussion with Niko, I think I'll either try to support him in his MIR-based implementation or wait until it's done.

**Comment by Manishearth** [comment]
SGTM

**Comment by llogiq** [comment]
Now that rustc has a much more advanced `eval_const` function, I think we can safely close this.
