### ISSUE TITLE
implementing an add/sub/mul/div method instead of Add/Mul/Sub/Div

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#218]
Perhaps if a type implements its own `add` with compatible arguments, suggest implementing `std::ops::Add` instead. Same for the other arithmetic `std::ops::*` traits.

**Comment by birkenfeld** [comment]
Good idea!

**Comment by Robzz** [comment]
Good thing you thought of it, the issue I opened and closed actually made me think of this too but I felt like opening an issue right after the other one was wrong. Now, I suppose *I* was wrong not to suggest an idea that may turn out to be good. To be sure for next time : would you consider opening issues without being 100% sure they're good ideas as a bad practice?

Sorry about the digression. Getting accustomed to open-source development is quite a process :) Back to the topic :

If someone were to implement this, it might be a good idea to check for other `ops::` traits that could be suggested in a similar fashion. I'm mostly thinking about Sub, Div and Mul, as the other operator overloads are, I believe, more rarely used. Still, `add` seems like a fairly straightforward case compared to the others, so I don't know.

Related though it is beyond the scope of this issue : it could also be a good idea to check for this for a couple of other quite common traits, for instance, `ToString` when detecting a `to_string` method. Or, although it sounds a lot more complicated (unrealistic even? I can't tell, I don't know enough), suggesting implementing `From<TypeName>` when encountering a `from_typename` method. If the arguments are compatible, as you mentioned, of course.

**Comment by llogiq** [comment]
Yeah, I just used `Add` because it's easy to type and I was on mobile. Of course, the other arithmetical operators also apply, and I suspect the lint won't get too much bigger if it catches them all..

Suggesting to implement `From` or `Into` would also work, but could be subtle because orphan rules sometimes forbid implementing `From` (simplified: if the target type is outside the current module). I'd like to have this in a different issue, though.

**Comment by Manishearth** [comment]
It's fine to open issues even if you're unsure about them, they can be discussed later.

**Comment by llogiq** [comment]
Yeah, I do that all the time. :smile:
