### ISSUE TITLE
Suggest implementing Copy on Clone types when possible

### ISSUE THREAD

**Issue by Robzz** [Manishearth/rust-clippy#244]
The documentation for `Copy` states 

> Generally speaking, if your type can implement `Copy` it should.

If this gets implemented, it might be worth it to add a note (on the wiki?) about removing Copy being breaking. I'm not sure whether such a lint should be `Allow` or `Warn`.

**Comment by Ryman** [comment]
I think this is already in rustc? `#![warn(missing_copy_implementations)]`

**Comment by llogiq** [comment]
Look at [my blog](https://llogiq.github.io/2015/07/30/traits.html#copy-and-clone) on that topic. Copy is quite subtle.

**Comment by Robzz** [comment]
@Ryman You're right apparently. I didn't notice, because it's `Allow` by default :( I can close this, I guess.
@llogiq Yeah, I just haven't encountered a case where I'd want move semantics over copy semantics yet. But you're right, there may be reasons for it.
