### ISSUE TITLE
Equal Expressions when using random number generator

### ISSUE THREAD

**Issue by Johnson-A** [Manishearth/rust-clippy#252]
src/magics.rs:127:25: 127:60 warning: equal expressions as operands to &, #[warn(eq_op)] on by default
src/magics.rs:127                 magic = rng.gen::<u64>() & rng.gen::<u64>() & rng.gen::<u64>();

The random number generator calls should not be treated like they're equal.

**Comment by birkenfeld** [comment]
This should already be fixed in master.

**Comment by Manishearth** [comment]
Let us know if this still occurs with an updated clippy!
