### ISSUE TITLE
Failure to build with Rust 1.4.0 Nightly (2015-08-30)

### ISSUE THREAD

**Issue by mgattozzi** [Manishearth/rust-clippy#256]
Clippy fails to build with the newest nightly compiler.
The problem being that syntax::ast::DefId is not defined. I grepped through the source code of rustc and looks to be nowhere in sight under libsyntax. It should be an easy fix if it's been moved and defined somewhere else.
![2015-08-30-062858_1366x768_scrot](https://cloud.githubusercontent.com/assets/3514399/9566803/06728202-4ee1-11e5-8f3f-48e456de0f93.png)

**Comment by llogiq** [comment]
They just moved it from middle to ast...

**Comment by birkenfeld** [comment]
No, they moved it *to* middle and we already fixed it in master :)

**Comment by birkenfeld** [comment]
Can be closed...
