### ISSUE TITLE
Never-looping loops

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#257]
This lint would warn on `loop`s with unconditional `break`s, because in that case, both `loop` and `break;` can be removed, leaving only a scope.

This would be either a remnant of some refactoring, code by one who doesn't know plain scope definitions or test cases for clippy lints. :smile:

**Comment by llogiq** [comment]
Of course we'd have to check for other `break` or `continue`s within the loop.

**Comment by birkenfeld** [comment]
Yes, that's probably useful.

Similarly `continue` at the end of the loop can be removed.

**Comment by llogiq** [comment]
True.

**Comment by Manishearth** [comment]
This should have macro checks, but otherwise sgtm
