### ISSUE TITLE
Extend `while_let_loop` to warn even if there are statements after `match`

### ISSUE THREAD

**Issue by Zarathustra30** [Manishearth/rust-clippy#262]
The implementation of `while_let_loop` is incomplete. In cases when additional statements follow the `match`, such as the following:
```
loop {
    let bi = match bodies.next() {
        Some(bi) => bi,
        None => break
    };
    additional_statement1(bi);
    additional_statement2();
}
```
the loop can still be replaced with `while let`
```
while let Some(bi) = bodies.next() {
    additional_statement1(bi);
    additional_statement2();
}
```
These snippets are slightly different in theory, but identical in practice.

**Comment by llogiq** [comment]
Good catch!
