### ISSUE TITLE
Organize lint groups

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#265]
[quoting](https://github.com/Manishearth/rust-clippy/issues/251#issuecomment-136318464) @Manishearth:

> IMO we should organize our lint groups more (perhaps start mentioning lint groups in the lint declaration and have the python script generate them). Have some "normal" (group: clippy) Warn lints, have some "zealous" (group: clippy_zealous) Allow lints, and then some "clippy_misc" lints for stuff like the above where the lints actually conflict

**Comment by llogiq** [comment]
I'd like the "zealous" group to be called `pedantic_clippy`. Also as birkenfeld (as I should have) found out, in the range-parentheses case, we don't have the option, as method calls actually require the parentheses.

**Comment by Manishearth** [comment]
:bike: :house: sgtm
