### ISSUE TITLE
into_string() is dead, long live to_owned()

### ISSUE THREAD

**Issue by kennytm** [Manishearth/rust-clippy#27]
Since rust-lang/rust#19741 is merged, `str.into_string()` is no longer available. The replacement seems to be `std::borrow::ToOwned::to_owned()`. The lint should be updated to this.

**Comment by Manishearth** [comment]
Looks like we came full circle on this `to_owned()` business :p

**Comment by Manishearth** [comment]
Wait, `to_owned()` just calls `to_string()`. Not good.

**Comment by Manishearth** [comment]
Okay, that got fixed.
