### ISSUE TITLE
wrong_self_convention vs. back-compat

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#282]
If one runs clippy against stable code, the `wrong_self_convention` lint suggests a rename. This should not be taken lightly, for it can break backwards-compatibility.

I have added some text to that effect to the wiki. Perhaps the lint message should give at least a hint to be careful.

**Comment by birkenfeld** [comment]
True. (We have a similar suggestion for the `should_implement_trait` lint.)

**Comment by llogiq** [comment]
@birkenfeld Also I think that `as_mut_`* should be allowed to take `&mut self`.

**Comment by llogiq** [comment]
Perhaps a solution would be to not warn on public items (perhaps put this into another lint that is `Allow` by default, so people can check if they don't promise stability yet).

**Comment by Manishearth** [comment]
Allow sgtm.
