### ISSUE TITLE
#![deny(warnings)]

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#287]
We should have a lint against this and it should `Deny`, because else it'd have to `Allow`.

**Why is this bad?** The build will break when the first API used is deprecated. Things out of control of the code may lead to warnings.

Optimally the lint should check if the attribute is within a `#[cfg(..)]` block. The lint should live in `src/attrs.rs`.

**Comment by Manishearth** [comment]
I'm not really fond of this lint. `#![deny(warnings)]` is a deliberate choice, taken by many repos.

Besides, cargo clips the warning levels of dependencies to `Warn`. Such things  are best addressed at the infra level.

**Comment by Manishearth** [comment]
Closing, given that cargo already solves this problem
