### ISSUE TITLE
False positive on len_without_is_empty: ExactSizeIterator

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#289]
On rust's `libcore/iter.rs`, our `len_without_is_empty` lint complains that ExactSizeIterator has no `.is_empty()` method. While this is in general a good idea for collections, even the `.len()` method only returns a lower bound. An `.is_empty()` method cannot work in all cases, and adds little value to the iterator.

Therefore I think we should check if the type has an `Iterator` bound and omit the lint in such cases.

**Comment by bluss** [comment]
The .len() on iterator must be exact if it's implemented though, so it could provide .is_empty(). But I don't think it's much use on iterators.

**Comment by llogiq** [comment]
ExactSizeIterator` now has `_.is_empty()`, so this issue is moot. Closing.
