### ISSUE TITLE
Nonsensical combinations on File APIs

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#297]
As seen from [RFC PR #1252](https://github.com/rust-lang/rfcs/pull/1252):
```
File.create_new(true).truncate(true)
```
Also mixing `create(_)` and `create_new(_)`, and possibly some others.

**Comment by Pyriphlegethon** [comment]
This would require some kind of data-flow analysis for more complicated examples (in the most general case this would be impossible). 
If this is just about function chaining and nobody is already working on it, I'd like to give it a try. :smile:

**Comment by Manishearth** [comment]
Yeah, function chaining.

**Comment by Pyriphlegethon** [comment]
I guess this can be closed?
