### ISSUE TITLE
Box<Vec<T>> warning triggered spuriously

### ISSUE THREAD

**Issue by maurer** [Manishearth/rust-clippy#31]
The `Box<Vec<T>>` warning appears to be being triggered when I box a closure (necessary in this case to make the struct `Sized`).

```
src/native_types.rs:93:13: 93:65 note: Vec<T> is already on the heap, Box<Vec<T>> makes an extra allocation
src/native_types.rs:93   pub run : Box<Fn(Vec<HValue>) -> Vec<HValue> + 'static + Send>
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by pythonesque** [comment]
This is (or should be) fixed now.

**Comment by llogiq** [comment]
I'll add a test to `tests/compile-fail/box_vec.rs`. If successful, I'll close.

**Comment by llogiq** [comment]
Yep, it's no longer triggered. Closing.
