### ISSUE TITLE
false positives on approx_const

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#311]
A funny thing is that `approx_const` is triggered on the constant definitions themselves when running on rust. This is obviously a false positive – how else could the constants have been defined? It's also quite easy to check (though it's also easy enough to disable the lint on checking rust).

In the same vein, the `f`{32, 64}`.is_nan()` functions are a perfect counterexample to `eq_op`, because the correct way to check for `NAN` is `x != x`.

**Comment by llogiq** [comment]
Revisitng this, it would probably be easiest to check the crate name – how do I get this?

**Comment by Manishearth** [comment]
You can use the Cstore from the Session to get the current crate's metadata (crateid = 0 I think).

**Comment by llogiq** [comment]
That throws an ICE, because the `unwrap` in `librustc/metadata/cstore.rs:130` fails.

**Comment by Manishearth** [comment]
Perhaps I got the crateid wrong then. If you can somehow get the did of the method declaration, that should be enough to get you the current crate

**Comment by llogiq** [comment]
Closing this, because it's both easier and faster to `-A approx_const -A float_cmp` when running on rustc.
