### ISSUE TITLE
Can't compile with Clippy, missing `rustc_front`

### ISSUE THREAD

**Issue by hawkw** [Manishearth/rust-clippy#315]
I added Clippy to my dependencies and added the `plugin` attribute to my crate. `$ cargo build` now yields the following error:

```
Compiling clippy v0.0.13
/Users/hawk/.cargo/registry/src/github.com-0a35038f75765ae4/clippy-0.0.13/src/lib.rs:11:1: 11:26 error: can't find crate for `rustc_front`
/Users/hawk/.cargo/registry/src/github.com-0a35038f75765ae4/clippy-0.0.13/src/lib.rs:11 extern crate rustc_front;
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `clippy`.
```

I'm using the v1.4.0 nightly Rust on Mac OS X 10.10.5:
```
$  rustc --version
rustc 1.4.0-nightly (fe9cef7da 2015-08-30)
$ cargo --version
cargo 0.5.0-nightly (1d0823b 2015-08-29)
```

**Comment by llogiq** [comment]
You'll need a newer nightly – thus rustc_front crate was added fairly recently.

Unfortunately, we're beholden to the latest nightly, let our development drifts too far away from rustc, whose unstable plugin API is our lifeline after all.

**Comment by hawkw** [comment]
Okay, I wasn't sure if this was a compatibility issue or not. I guess I should've grabbed a newer Rust before reporting, sorry.

**Comment by llogiq** [comment]
No problem. We're here to help. :smile:

**Comment by kbknapp** [comment]
Seems to have popped up again? 

```
$ cargo build
Compiling clippy v0.0.61
[..]/github.com-88ac128001ac3a9a/clippy-0.0.61/src/lib.rs:23:1: 23:26 error: can't find crate for `rustc_front` [E0463]
[..]/github.com-88ac128001ac3a9a/clippy-0.0.61/src/lib.rs:23 extern crate rustc_front;
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
error: Could not compile `clippy`.

To learn more, run the command again with --verbose.

$ rustc -V
rustc 1.9.0-nightly (bf5da36f1 2016-04-06)
```

**Comment by mcarton** [comment]
@kbknapp yes, and it will pop every time rustc API changes. See https://github.com/Manishearth/rust-clippy/issues/841 and https://github.com/Manishearth/rust-clippy/pull/842
