### ISSUE TITLE
container.len() == 0

### ISSUE THREAD

**Issue by lfairy** [Manishearth/rust-clippy#32]
For most types, this can be rewritten as `container.is_empty()`.

cc rust-lang/rust#23682

**Comment by lfairy** [comment]
As a first approximation, we can warn when the self type is in `collections`.

If it's easy enough to check for an `.is_empty()` method, we can do that instead.

**Comment by llogiq** [comment]
So, I now know how to get at the type (though I'm not sure what the exact contents would be), so how do we find out if the type has an `is_empty()` method?

**Comment by Manishearth** [comment]
I assume you go through the method map? Everything regarding type check and resolution is done through the tcx (type `ctxt`). Check out `middle::ty` for a ton of helper functions.

**Comment by llogiq** [comment]
I know how to get the type definition (via `expr_ty`), but I'm a bit lost on how to go from there to the MethodMap. Do I construct a `MethodCall` via its `expr` and use that to query the MethodMap?

**Comment by Manishearth** [comment]
I'm not sure. Iterating through the `tcx.impl_or_trait_items` entry for the defid of the given type might work.

You'll have to explore `middle::ty` and `ctxt` to get this I guess :)

**Comment by llogiq** [comment]
I've run into some wrestling with typeck, but at least I feel like I'm on the right track.

I'll see once the code compiles, anyway. :smile: However, it's getting late, so I'll resume tomorrow.

**Comment by llogiq** [comment]
Now it compiles, but the type lookup fails for the simple case `let x = [1, 2]; if x.len() == 0 { … }`. I cannot figure out how to get from the DefLocal to a slice of its `ImplOrTraitItemId`s. Probably the whole approach is wrong.

**Comment by Manishearth** [comment]
I've never really played with this so you're basically on your own here, sorry :) Poking people in #rust-internals may help

**Comment by llogiq** [comment]
The problem is I'd either need to copy large swaths of typeck *and* patch rustc to allow me to access some private fields/methods, or just wait until the core team makes this available for lints.

The latter part opens up some of my time to try and implement some other things, so I guess I'll wait.

**Comment by llogiq** [comment]
The lint in #60 basically encodes that every impl that has `.len ()` should have `.is_empty()`, so we can get by without method lookup at the cost of possible false positives.

This is intended as a stop-gap solution, but may turn out to be good enough should we surmise that the cost of method lookup is too high.
