### ISSUE TITLE
ICE

### ISSUE THREAD

**Issue by durka** [Manishearth/rust-clippy#322]
Not sure whether this is a clippy bug or a rustc bug. https://gist.github.com/durka/3f7bd5a68ea50a19d837

**Comment by durka** [comment]
Never mind. Caused by running clippy with a different version of rustc than the one used to compile it.

**Comment by llogiq** [comment]
I knew I'd seen it [somewhere](https://llogiq.github.io/2015/09/06/clippy.html).

Perhaps we should have a warning in the README or on the wiki.
