### ISSUE TITLE
Idea: warning on empty ranges

### ISSUE THREAD

**Issue by Wilfred** [Manishearth/rust-clippy#330]
I have occasionally written `for x in 10..0` when I meant `(0..10).rev()`. Would this make sense as a clippy warning?

**Comment by llogiq** [comment]
Seems to be at least somewhat related to #96.

If this is going to grow into a larger range-iter lint, we should be aware of all edge cases arising from .rev() and .step_by().

**Comment by Manishearth** [comment]
Fixed in https://github.com/Manishearth/rust-clippy/pull/331
