### ISSUE TITLE
Change our tagline

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#339]
I think clippy is no longer "A bunch of lints to help avoid newbie pitfalls." – we have found (and fixed) a good number of issues in both [servo](164) and [rustc](278) code bases. Both code bases are arguably not written by newbies. Also some may find the title demeaning.

So what should we use instead? Some ideas:

* A bunch of Lints to catch common mistakes and improve your Rust code
* Let's Improve your Code
* Dust off your Rust
* Your Helpful Rust Code Checker

@Manishearth @birkenfeld what do you think?

**Comment by Manishearth** [comment]
First one sgtm

**Comment by llogiq** [comment]
Ok. @Manishearth you'll have to change it; I lack the access rights to change project setup.

**Comment by Manishearth** [comment]
Done
