### ISSUE TITLE
rustfmt clippy

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#342]
Let's try and run rustfmt on clippy.

Considering that I clippy'd rustfmt some time ago and my PR was accepted, it's only fair that we return the favor :smile:

**Comment by llogiq** [comment]
So given the current results, I'm quite lukewarm on this for now. At least we've opened a few issues on their tracker. :smile:

**Comment by Manishearth** [comment]
I'm actually okay with most of this. Don't mind merging.
