### ISSUE TITLE
rustc as of 2015-09-24 fails to build clippy

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#348]
I believe this is a rustc issue, but I first wanted to make sure I'm correct before submitting an issue to rust. Also I have too much work today, so I'm putting this here.

If I prefix the UnOps with `UnOp::`, the compiler crashes, btw.

@Manishearth any idea?

**Comment by Manishearth** [comment]
UnUniq was removed. https://github.com/Manishearth/rust-clippy/tree/rustup works for me, on rust master. Haven't yet downloaded the nightly.

**Comment by llogiq** [comment]
Works for me. I'm merging that.

**Comment by Manishearth** [comment]
sgtm

**Comment by Undeterminant** [comment]
I'm getting more UnUniq errors in the latest nightly (09-27-2015).

**Comment by birkenfeld** [comment]
There is no `UnUniq` left in the clippy codebase. Are you sure you have the latest master?

**Comment by Manishearth** [comment]
There are some other errors though; fixed them.

**Comment by birkenfeld** [comment]
Yes, I noticed that. Is that change really necessary, or could we get a patch into rustc that allows `Name == &str` again?

**Comment by Manishearth** [comment]
I left a comment on the PR that broke it. But it seems intentional.

**Comment by Undeterminant** [comment]
Oh, I see the problem. It's not updated on cargo, but if I link to the git repo, it works.
