### ISSUE TITLE
Reference to vec should be slice

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#35]
`&Vec<T>` should usually be `&[T]` to save one pointer.

**Comment by jdm** [comment]
Similarly, &String vs &str?

**Comment by llogiq** [comment]
Yeah, I made this mistake too, recently. Guess I *am* a newbie. I'll take it.

**Comment by llogiq** [comment]
Pushed on master. This only handles &Vec<_> as of now, I'll add jdm's suggestion next. I'll leave this open until I'm done with that.

**Comment by llogiq** [comment]
And I just added &String matching. Case closed :smile:

**Comment by Manishearth** [comment]
:D 

Note: try to make PRs before merging to master (feel free to hit the merge button on them though) -- this way I can review the code eventually.

**Comment by llogiq** [comment]
Ok, I'm going to do this for the next ones.
