### ISSUE TITLE
Clippy's output looks somewhat ugly (to me)...

### ISSUE THREAD

**Issue by Wafflespeanut** [Manishearth/rust-clippy#350]
Have a look at this warning...

![ugly](https://cloud.githubusercontent.com/assets/6691262/10118178/eda867e0-648f-11e5-86d8-d0f7c4746ec0.png)

Now, see this pretty warning...

![pretty](https://cloud.githubusercontent.com/assets/6691262/10118179/f0fdec26-648f-11e5-91a1-95a06e3e2e67.png)

What I mean is that it'd be nice and visually helpful (at least, while checking large files) to have some space for copy-pasting stuff directly, and because we're linting. Also, this only requires `format!`ting with a newline at the respective helper methods like `span_lint` and `span_and_help_lint` at `util.rs`

**Comment by Manishearth** [comment]
> Also, this only requires format!ting with a newline at the respective helper methods like span_lint and span_and_help_lint at util.rs

Not really, since only some of these output "try..." snippets. But I'm open to the change.

**Comment by Wafflespeanut** [comment]
actually, that should be `span_help_lint`

**Comment by birkenfeld** [comment]
This one is pretty much solved now by using RUST_NEW_ERROR_FORMAT=1 (until that is the default). If you disagree, please reopen.
