### ISSUE TITLE
Mutex<bool>...

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#352]
...and other types for which an std::sync::atomic type is available.

For an advanced version we could try to suggest a performances optimal ordering depending on use case, but SeqCst will do in any case.

**Comment by fhartwig** [comment]
I'd like to have a go at this if nobody is working on it yet.

**Comment by llogiq** [comment]
Cool.

**Comment by llogiq** [comment]
Revisiting this, there are cases where people use `Mutex` *for the locking behavior*. I'm not sure how to detect this.

**Comment by Manishearth** [comment]
It's usually `Mutex<()>` then. We can recommend that. `Mutex<bool>` has an additional lock bit cost.
