### ISSUE TITLE
Propose vec![] instead of Vec::new()

### ISSUE THREAD

**Issue by Wilfred** [Manishearth/rust-clippy#355]
I think `vec![]` is cleaner, and it's easier if you later decide you want to initialise with some values. Do you agree?

**Comment by Manishearth** [comment]
I'm not sure if there's a clear benefit here. Also, I think a large amount of people explicitly prefer the reverse.

**Comment by llogiq** [comment]
There's always place for an `Allow` lint, though.

**Comment by birkenfeld** [comment]
But then I want two `Allow` lints, one suggesting `vec![]` instead of `Vec::new()`, and one suggesting `Vec::new()` instead of `vec![]`.

**Comment by Manishearth** [comment]
clippy_pedantic: You can run, but you can't hide!

**Comment by Manishearth** [comment]
Note that `vec![]` isn't something that can be easily caught.

**Comment by birkenfeld** [comment]
And conversely, easy to spot with a `grep`.

**Comment by Manishearth** [comment]
Theoretically with the new lint framework we could add pre-expansion lints. But that seems like something that isn't going to be used much.

**Comment by birkenfeld** [comment]
I'm not in favor of this lint. I for one like `Vec::new()` better for the symmetry with `Vec::with_capacity`.

**Comment by Manishearth** [comment]
Agreed.

**Comment by Wilfred** [comment]
Fair enough.  :)
