### ISSUE TITLE
Travis supports rust now. 

### ISSUE THREAD

**Issue by ehiggs** [Manishearth/rust-clippy#358]
There are a lot of crates that download rustup and install rust before building. This isn't needed since travis-ci support rust now. An example PR to fix a `.travis.yml` file can be found [here](https://github.com/iron/urlencoded/pull/55).

**Comment by Manishearth** [comment]
We already use this.

https://github.com/Manishearth/rust-clippy/blob/master/.travis.yml#L1

**Comment by ehiggs** [comment]
No, I mean clippy should see if projects download rustup. They should use the lint warning to let them know they should update to use builtin travis support.

**Comment by Manishearth** [comment]
Oh. It's a compiler plugin, and while it can feel around for files, it's not ideal (and brings up trust questions). I'd prefer to let clippy check code only.
