### ISSUE TITLE
No RingBuf

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#363]
We recommend a RingBuf instead of a linked list, but it has been removed from the stdlib. crates.io doesn't yield anything useful either. A google search gives one library on github (https://github.com/danburkert/rust-ringbuf) but it was last updated > 1 year ago so of course fails to compile horribly.

Time to remove the suggestion, or implement a RingBuf ourselves :)

**Comment by Manishearth** [comment]
@Gankro is there something better we should suggest in place of LinkedList?

**Comment by killercup** [comment]
@birkenfeld wasn't RingBuf just renamed to VecDeque?

**Comment by birkenfeld** [comment]
Well, so much the better. I won't bother to create a PR for this.

**Comment by Manishearth** [comment]
Np. Minor fixes don't need PRs :smile:
