### ISSUE TITLE
Prefer `.cloned()` over `.map(|x| x.clone())`

### ISSUE THREAD

**Issue by frewsxcv** [Manishearth/rust-clippy#367]
https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.cloned

https://doc.rust-lang.org/nightly/core/option/enum.Option.html#method.cloned

**Comment by pierrechevalier83** [comment]
see https://github.com/servo/servo/pull/7946

**Comment by pierrechevalier83** [comment]
I didn't get it right... I got confused with https://github.com/servo/servo/issues/7906 as explained in my comment there... Please, ignore! (I'm well intentioned, I swear... just a bit stupid...)

**Comment by wartman4404** [comment]
I didn't even realize `cloned()` was a thing!  I'd like to tackle this, if I'm not being too greedy with easy/medium issues.

**Comment by Manishearth** [comment]
Sounds good to me!

Feel free to take as many mediums as you want. Easies too, but leave a couple of those for others :smile:

**Comment by sanxiyn** [comment]
This can be closed, being fixed by #427.
