### ISSUE TITLE
incorrect use of min/max

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#38]
(Analogous to the bad_bit_mask lint, we can detect min(x, max(y, _)) where x < y (this will always return x) or vice versa.

**Comment by llogiq** [comment]
This would be simple enough for int and perhaps float values. The main problem is how to find out if a literal is greater or lower than another. We'd need a generic cmp_lit method, which means I'll need to learn a bit more about literals.

**Comment by llogiq** [comment]
Actually, using const folding, this is now rather easy.

**Comment by Manishearth** [comment]
(Example of const folding is https://github.com/Manishearth/rust-clippy/blob/master/src/identity_op.rs#L47)

**Comment by llogiq** [comment]
I should add that `Constant`s now implement `PartialOrd`, so they can meaningfully be compared using normal comparison operators (like `>` or `<=`).
