### ISSUE TITLE
`while_let` loop still has bugs!

### ISSUE THREAD

**Issue by Wafflespeanut** [Manishearth/rust-clippy#383]
For the following code,

``` rust
loop {
    let foo = match y {
        Some(x) => x,
        None => break,
    };
    let bar = Some(foo);
}
```

clippy seems to suggest, 

``` rust
while let Some(x) = y {
    let bar = Some(foo);
}
```

It's actually the wrong `let` binding. The code which lives at [`src/loops.rs`](https://github.com/Manishearth/rust-clippy/blob/master/src/loops.rs#L202), seems to print the match arm directly, instead of checking whether it's the right pattern.

**Comment by Manishearth** [comment]
Could you fix this in your current PR?

**Comment by Wafflespeanut** [comment]
alright :)

**Comment by mcarton** [comment]
I’m closing, see #675.
