### ISSUE TITLE
const fn calling non-const fn

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#399]
This came up in a [rust-users discussion](https://internals.rust-lang.org/t/how-to-handle-constants-in-the-compiler/2543/15).

Basically if we have a `const` function calling a non-`const` function, the `const` declaration is worthless.

**Comment by Manishearth** [comment]
The compiler catches you when a `const` function calls non const things. http://is.gd/aB9HjI

**Comment by llogiq** [comment]
Cool. I should have tested this before opening the issue.
