### ISSUE TITLE
Approx_const needs tweaking

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#404]
It doesn't warn on `3.14`, needs more digits.

I guess the epsilon divisor should be 99 or something? Or, have a different epsilon per array element?

3.14 is almost always pi. 2.71 is often not e

**Comment by llogiq** [comment]
I agree that it's not too flexible currently. We could have lower and upper bounds – less calculation to do. However, I disagree that 3.14 should be pi – most people I know will at least use 3.1415. Then again, I'm not into physics, so I may be accustomed to fairly precise calculations... :smile:

**Comment by Manishearth** [comment]
I'm a physics student. I and other around me use 3.141593 when too lazy to find the actual const, but I've seen lots of programmers use 3.14.

**Comment by Wafflespeanut** [comment]
Agreed, we use 3.14 almost all the time!

<sup> /me <-- engineering undergrad :P</sup>

**Comment by llogiq** [comment]
Ok, so we either need different lint levels for the CS, Physics and Maths department and for Engineering... :smiley:

But yes, using an interval will probably be a nicer solution. Now we only need to come up with suitable bounds (inclusive). How about the following?

constant | minimum bound | maximum bound
-----|-----|-----
PI| 3.14 | 3.142
E | 2.71 | 2.72
SQRT2 |1.40000001 | 1.42
FRAC_1_SQRT_2 | 0.70000001 | 0.71

More?

**Comment by Manishearth** [comment]
I think the last three should be at three digits.

**Comment by iKevinY** [comment]
Assuming nobody else is already working on this, I'd like to have a go at implementing it once there is a consensus on its implementation.

**Comment by llogiq** [comment]
You got it. The broad consensus is to change the KNOWN_CONSTS tuples to `(f64, f64, &'static str)` where the first two values denote the minimum and maximum bound.

Feel free to implement the details that haven't been discussed however you see fit, or ask here if you are unsure.

@Manishearth (and everyone else) Please just update the table above with the values you have in mind.

**Comment by iKevinY** [comment]
Alright, seems straightforward enough. I'll submit a preliminary PR shortly with some somewhat sensible values for the bounds until we decide on how precise to be.

**Comment by llogiq** [comment]
Great! I look forward to your PR.

**Comment by llogiq** [comment]
I think our choice of constants is good enough, otherwise we'd get issues about it. :smile:
