### ISSUE TITLE
A bad_api lint of some sort to catch issues like safe fn taking raw-ptr

### ISSUE THREAD

**Issue by nagisa** [Manishearth/rust-clippy#410]
A safe function taking a raw pointer yells unsafety at me. Might be good to have issues like this linted against.

**Comment by Manishearth** [comment]
I'm not really sure of this. There are plenty of functions which might do the requisite checking.

**Comment by nagisa** [comment]
One case where this isn’t applicable is extern functions. Rust functions have really no reason taking raw pointer over a reference.

**Comment by Manishearth** [comment]
Yes they do. In cases when you're sending pointers across threads, for example. We do this in Servo, with `Trusted<T>`

**Comment by Manishearth** [comment]
(Or at least, that's how it used to work in Servo before some other changes happened)

**Comment by nagisa** [comment]
Basically replaced by https://github.com/Manishearth/rust-clippy/issues/411
