### ISSUE TITLE
Catch public safe functions which dereference pointer arguments

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#411]
If:

 - a function is public but not `unsafe`
 - has a raw pointer argument
 - dereferences the pointer argument

The function should probably be marked `unsafe`, since for an arbitrary raw pointer, there's no way of telling for sure if it's valid.

See also: https://github.com/rust-lang/rust/issues/29257

**Comment by dimbleby** [comment]
Public functions are certainly most important here, but I don't see why the proposed lint shouldn't apply also to private functions.

I understand that there may be guarantees internal to some library such that an otherwise-unsafe private function is only ever called with inputs that in fact cause it to behave safely.  

But, surely, the "otherwise-unsafe" function is in fact still unsafe?  The burden is on its callers to guarantee that they're providing good inputs.  This is what `unsafe` is for, isn't it?

**Comment by Manishearth** [comment]
Because most safe abstractions are unsafe from within their module due to privacy.

For example, setting a vector's capacity is an unsafe operation, but you can only do that from within the module, so it's fine.

If we didn't have the pub restriction this warning would warn on most legitimate uses of `unsafe` too, as mentioned above.

> But, surely, the "otherwise-unsafe" function is in fact still unsafe? The burden is on its callers to guarantee that they're providing good inputs.

The callers are also scoped to the module because it's private. So there's a limited set of callers, which probably call the function with other invariants in mind. It's fine.

**Comment by Gankro** [comment]
@Manishearth I think the idea is that internal methods that rely on invariants should still be marked as unsafe. However it should be noted that we've kinda considered it "ok"... ish... to abuse unsafe within the privacy boundary. libcollections did this for a long time... might still. If you're doing pervasively unsafe things, you really don't need anyone telling you that you are. Shut that all down and get to codin'.

It's a weird situation.

**Comment by Manishearth** [comment]
@Gankro but that's putting lipstick on a pig, because we don't have the notion of "unsafe" fields which is often the root of this module-scoped unsafety.

**Comment by Gankro** [comment]
Nah DList for a long time had a "safe" function which was just like "lol dereference a raw ptr". Those fields could become invalid without ever touching them -- just free the thing they point to (which if it's an Option<Box>) is totally safe. I guess if you made every field in DList unsafe they'd have to do something `unsafe` to invalid one of those pointers... but like... man what have we even gained?

**Comment by Manishearth** [comment]
I'm not saying we _should_ have unsafe fields, I'm saying that the lack of unsafe fields is more of a problem than private functions which deref pointer arguments in the same space.
