### ISSUE TITLE
Add a function/method length lint

### ISSUE THREAD

**Issue by mrmonday** [Manishearth/rust-clippy#421]
It would be useful to be able to place a restriction on the length of functions, and give a message such as "This function is 1000 lines long - consider breaking into a number of smaller function calls".

**Comment by Manishearth** [comment]
Probably should be clippy_pedantic, but otherwise +1

**Comment by Undeterminant** [comment]
isn't this covered by `cyclomatic_complexity`?

**Comment by Manishearth** [comment]
This is.
