### ISSUE TITLE
Suggest 'map_or(a, b)' over 'map(b).unwrap_or(a)'

### ISSUE THREAD

**Issue by frewsxcv** [Manishearth/rust-clippy#424]
~~Same goes for `map_or_else(a, b)` with `map(b).unwrap_or_else(a)`~~

**Comment by frewsxcv** [comment]
And also

* https://doc.rust-lang.org/nightly/core/option/enum.Option.html#method.ok_or
* https://doc.rust-lang.org/nightly/core/option/enum.Option.html#method.ok_or_else

**Comment by devonhollowood** [comment]
I can take a look a this.

**Comment by Manishearth** [comment]
@devonhollowood Sure!

https://github.com/Manishearth/rust-clippy/blob/master/src/methods.rs#L41 is where you'll need to make the changes (see CONTRIBUTING.md for general tips). More or less the same procedure as the unwrap check -- see if the method name matches, then see if it `match_type`s `Option`.

Note that here we have two nested calls. `map(b).unwrap_or(a)` will be `methodcall(unwrap_or, methodcall(map, b))` so you'll need more checking in the match. The docs for Expr_ should help if you're still confused.

Let me know if you need more help!

**Comment by Manishearth** [comment]
@frewsxcv What exactly did you have in mind for the ok_or and ok_or_else methods?

**Comment by frewsxcv** [comment]
> @frewsxcv What exactly did you have in mind for the ok_or and ok_or_else methods?

Nevermind about those. I think I made up the existences of `ok_or` and `ok_or_else`

**Comment by untitaker** [comment]
Can be closed due to #468
