### ISSUE TITLE
Deriving only one of Hash/Eq considered harmful

### ISSUE THREAD

**Issue by Gankro** [Manishearth/rust-clippy#430]
If you derive Hash, but implement (Partial)Eq manually, you're probably doing it wrong, because those two need to agree for e.g. HashMap to work right.

**Comment by Manishearth** [comment]
This basically needs to look for the `automatic_derive` annotation on impls and compare.

**Comment by apasel422** [comment]
@Manishearth I assume the best way to do this is to have `LateLintPass::check_struct_def` query the context for the presence of `PartialEq` and `Hash` impls for the struct/enum and then see if one contains the `automatic_derive` annotation and the other does not. We can extract this data from `cx.tcx` more efficiently than recomputing it ourselves, right?

**Comment by Manishearth** [comment]
Yes. I don't know exactly which side tables it's in the tcx, but the info should be there.

Actually, a check_item for partialeq impls might be easier.

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rfcs/issues/1499 suggests that this issue is not yet resolved, since only derived `Hash` + implemented `PartialEq` is linted, but not derived `PartialEq` + implemented `Hash`
