### ISSUE TITLE
Lint on blocks being in if conditions

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#434]
```
if {cond} {
 // stuff
}
```

isn't really Rust style. The braces should be omitted if possible (if the block is just a single expression), and if not the condition should probably be calculated beforehand.

This is a pretty easy lint, just needs to `check_expr` for ExprIfs with an ExprBlock as their condition. If the block has one expression and no statements, suggest removing the braces, else, suggest moving the condition calculation up.

**Comment by Manishearth** [comment]
This can be done as an EarlyLintPass like precedence.rs, btw.

https://github.com/Manishearth/rust-clippy/blob/master/src/collapsible_if.rs contains a similar lint.

**Comment by jmquigs** [comment]
Feedback welcome on the above commit, there are some things I'm not sure about in there (marked with TODO)

**Comment by Manishearth** [comment]
Feel free to preemptively open a PR which we can iterate on :smile:

**Comment by frewsxcv** [comment]
I think this was done in #464
