### ISSUE TITLE
Use `span_suggestion` instead of manually building suggestions

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#442]
http://manishearth.github.io/rust-internals-docs/rustc/session/struct.Session.html#method.span_suggestion

See, for example, the suggestion you get for http://is.gd/5k86CL, it's built by running span_suggestion with `format!("move {}", snippet_for_closure)`.

**Comment by sanxiyn** [comment]
laumann/compiletest-rs#30 is merged. Waiting on the new version to update dependency.

**Comment by oli-obk** [comment]
I think we're doing this everywhere now.
