### ISSUE TITLE
integer remainder modulo one

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#45]
Again, nicked from findbugs.

**Comment by birkenfeld** [comment]
What about the commit(s) referenced here - seems to be in the repository but not reachable via master? Accident or intentional?

**Comment by Manishearth** [comment]
They're from https://github.com/Manishearth/rust-clippy/pull/78, which has merge conflicts. Marking as assigned to @mattyhall; I forgot about that PR.

**Comment by Manishearth** [comment]
Fixed in #78
