### ISSUE TITLE
print!("..\n") instead of println!("..")

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#455]
The latter is more readable and will do the right thing on all systems, whereas the former only works on UNIX, IIRC.

The hard thing is the macro expansion.

**Comment by jmquigs** [comment]
I'll give this a try.  Since I use windows a lot, I occasionally have line-ending rage.  
Should there be related work for format!, and info!, etc from the log crate?  Sometimes people will use embedded newlines in the format specifiers for those.

**Comment by llogiq** [comment]
Yeah, probably match some fmt function (look at `-Z ast-json` output for a code example) and check if a literal contains `\n`.

**Comment by Manishearth** [comment]
Play around with `-Zunstable-options --pretty=expanded`, see what `println!()` expands to. This might be hard to detect. You can use the NameAndSpan in ExpnInfo(https://github.com/Manishearth/rust-clippy/blob/master/src/utils.rs#L69) to find the name of the macro some code came from. (` cx.sess().codemap().with_expn_info(span.expn_id, |info| ...)`)

If you can come up with a utility method which desugars `format!` calls that would be amazing

**Comment by jmquigs** [comment]
Thanks folks, that was very helpful.  I have this working at a basic level as an EarlyLintPass, but I need to clean it up a bit.  

I wanted a newline constant that I could suggest for the format! case, so I looked at what println! does.  Am I going blind or does it actually just drop a "\n" in there?
https://github.com/rust-lang/rust/blob/22e31f10c22112b486f4999f90e4ba9c7e23b9b6/src/libstd/macros.rs#L119 . If so that seems like a bug :smile:

Re desugaring utility, I'm not sure what you are after here...can you elaborate a bit?

**Comment by Manishearth** [comment]
Dropping a `\n` there sounds about right.

By desugaring utility I meant a function that takes in an AST node, determines if it's a format/print/etc expansion, and if so, finds out the original argument list and returns that.

**Comment by jmquigs** [comment]
Ah, ok.  For some reason I thought println! would do a platform-specific line ending ("\r\n" on windows).

Re utility function, I basically have the pieces of that, but right now my detection just involves looking at the format string itself, not any of the arguments.

**Comment by Manishearth** [comment]
Oh, the platform specific thing sounds wrong. Feel free to file a Rust bug (I'll do it if you don't want to).

**Comment by jmquigs** [comment]
Sure, I'll file it.

**Comment by jmquigs** [comment]
https://github.com/rust-lang/rust/issues/30048

**Comment by llogiq** [comment]
For the record, I've [asked](https://internals.rust-lang.org/t/pre-rfc-a-format-spec-for-newline/2934) a similar questioning on internals where it was posited that windows can mostly deal with `\n` nowadays.

**Comment by jmquigs** [comment]
Yeah, its probably fine.  I think golang does the same thing.  

It only matters for this ticket in that if someone has \n in a format! I can either 1) ignore it, or 2) tell them to replace it with...something.  Perhaps if that bug is marked as won't-fix, I'll just ignore it.

**Comment by jmquigs** [comment]
As @Manishearth suggested, this is hard to detect.  I don't see a way to differentiate print! and println!
This statement:
```rust
println!("Sure, fine\n");
```
Expands to an expression like this:
```
expr(14: ::std::io::_print(::std::fmt::Arguments::new_v1({
                                                    static __STATIC_FMTSTR:
                                                           &'static [&'static str]
                                                           =
                                                        &["Sure, fine\n\n"];
                                                    __STATIC_FMTSTR
                                                }, &match () { () => [], })))
```
I can't tell if it is a call to print! with two newlines, or a call to println! with just one.  If I look up the macro name with ```cx.sess().codemap().with_expn_info``` I see `print` and `format_args`, but never `println`.  In fact it seems like println! is expanded by an earlier operation.  Are macros processed in multiple passes?

**Comment by llogiq** [comment]
Exactly. Each macro invocation will lead to one expansion which may well expand further. I think there's some way to get the expansion chain, but I'm on mobile, so...

**Comment by frewsxcv** [comment]
I think the title of this issue is worded backwards

**Comment by mcarton** [comment]
@jmquigs do you still want to work on this? We’ve pretty much [solved the problem of knowing whether we’re in `print!` or `println!`](https://github.com/Manishearth/rust-clippy/blob/2abb775de5bed06722ef0d9d14488d6e8777842f/src/print.rs#L49-L57).

**Comment by jmquigs** [comment]
@mcarton, I'm not working on this right now, so go ahead.
