### ISSUE TITLE
(== or !=) exact comparison to f32/f64

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#46]
As we all know, floating point operations carry the risk of rounding errors, thus comparing a float with `==` is asking for trouble. Suggest `abs(x - y) < epsilon` (for some value of epsilon) instead.

**Comment by Manishearth** [comment]
I would suggest this be allow by default fwiw.

**Comment by llogiq** [comment]
No problem, but why?

**Comment by Manishearth** [comment]
I dunno, it might get overly annoying. Though perhaps that's what we want :)

**Comment by llogiq** [comment]
Why would it get annoying? This is one of the most basic mistakes to make with floating point arithmetic, and once you know about it, you simply avoid it. Agreed, it may not be too simple, as one has to decide on a good value for epsilon (though `max(x, y) / (1 << bits)` for some number of bits depending on your f*nn* type is often a perfectly fine default).

Honest question: Do you work a lot with IEE754 arithmetic and if so, do you tend to compare values with `==`?

**Comment by Manishearth** [comment]
Yeah, on thinking about it, let's keep it on warn. For my simulations all my equality checks were epsilon-y.


FWIW there's an EPSILON constant in the stdlib somewhere though that's a constant.

**Comment by llogiq** [comment]
Closed in PR #47
