### ISSUE TITLE
Extend match_ref_pats to handle if let

### ISSUE THREAD

**Issue by Wilfred** [Manishearth/rust-clippy#466]
When doing a bulk refactoring, I sometimes end up with code of the form:

```rust
if let &Foo = &bar {
```

It would be nice if `match_ref_pats` handled this. I think it would even be applicable to `&x == &y` too.

**Comment by llogiq** [comment]
Note that this `&x == &y` is not necessarily the same as `x == y` – the latter takes `x` and `y` by value, whereas the former doesn't. The `if let` case seems a bit more clear to me, because the match doesn't move unless you take some value out of it.

**Comment by Wilfred** [comment]
Thank you! :)
