### ISSUE TITLE
couple of lints missing from wiki

### ISSUE THREAD

**Issue by durka** [Manishearth/rust-clippy#467]
There are 11 lints with no entries on the wiki page (so the links from README.md are broken):

- [x] mutex_atomic
- [x] mutex_integer
- [x] needless_update
- [x] no_effect
- [x] ok_expect
- [x] temporary_assignment
- [x] unstable_as_mut_slice
- [x] unstable_as_slice
- [x] useless_transmute
- [x] while_let_on_iterator
- [x] wrong_pub_self_convention

**Comment by llogiq** [comment]
Yeah, usually I do the wiki entries, but I got swamped with work recently, so I'm somewhat behind schedule.

Perhaps we should script this from doc comments and require that each lint submission has the comments in the required format?

**Comment by llogiq** [comment]
I have done just that. Now we only need to add some text to CONTRIBUTE.md to the effect of "put this comments before your `declare_lint!` declaration.

**Comment by durka** [comment]
I assume you know already, but looking at the wiki the script is not quite working yet...

**Comment by Manishearth** [comment]
I think the script hasn't been run yet :smile:

**Comment by llogiq** [comment]
It has, but I missed the end of the code block in `boxed_local`. It's fixed now.

**Comment by llogiq** [comment]
Also I just added the remaining missing doc comments.
