### ISSUE TITLE
warn about calling a closure in the same expression where it's defined

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#476]
super minimal example: `(|| 42)()`. A closure needs to either be stored in a binding or passed to a function. But calling it in the same expression where it's defined is just noise.

This can probably be extended to other constructors, too:
* Create a struct/tuple and access a field in the same expression
* match on an enum variant value created in the expression after the `match`

**Comment by Manishearth** [comment]
This can be an AST lint checking for ExprCalls where the target is an ExprClosure.

**Comment by martiansideofthemoon** [comment]
@Manishearth, I think I understand the problem here and would like to work on it. A few questions.
1. I suppose each lint is implemented in a new file. Is this true? Would it be so in this case?
2. I see two `impl`, a `LintPass` and a `LateLintPass`. What's the difference between the two?
3. So reading the blogpost, I realized that I need to implement a `check_item` function. So it has an `&Item` reference. What exactly is happening here? Does clippy scan through each expression and store it in `item`? Also what's `item.ident.as_str()`? Couldn't really understand the Rust documentation :(

**Comment by Manishearth** [comment]
> 1. I suppose each lint is implemented in a new file. Is this true? Would it be so in this case?

Not necessarily. This is simple enough that it can go into `early_misc`. Most files have multiple lints

>  I see two impl, a LintPass and a LateLintPass. What's the difference between the two?

LateLintPass inherits from LintPass; see the documentation (http://manishearth.github.io/rust-internals-docs/rustc/lint/trait.LateLintPass.html). LintPass is a trait that abstracts over functionality common to _all_ lint passes, and contains an impl of the `get_lints()` method that lists the lints the pass provides. LateLintPass and EarlyLintPass are two kinds of lint passes, run at different times during compilation. LateLintPass has access to resolved type info and everything, whereas EarlyLintPass only operates on the AST. This issue doesn't need anything more than AST checking, so an early pass is what you need.

> What exactly is happening here? 

This is basically a "visitor pattern". The AST is a tree of nodes, where the nodes are things like items (functions, impls, struct definitons, enum definitions, etc), statements, expressions, types, literals, etc. Your lint pass "visits" the tree as a depth-first search, and calls check_foo on each node of type Foo.

`item.ident.as_str()` takes the identifier corresponding to an item and converts it to a string. In case of a struct or enum definition, this identifier is the struct/enum name. Same for functions. I think that the identifier is either empty or the same as the type name for an impl.

Look at the FooKind enums to see what each type of AST node can be: http://manishearth.github.io/rust-internals-docs/syntax/ast/enum.ItemKind.html

**Comment by mcarton** [comment]
> 3. I realized that I need to implement a check_item function

You want `check_expr` here. Items are named stuffs (functions, types, etc.).
