### ISSUE TITLE
Panic in cyclomatic complexity lint

### ISSUE THREAD

**Issue by shahn** [Manishearth/rust-clippy#478]
The following reduced code produces a panic:

    #![feature(plugin)]
    #![plugin(clippy)]
    
    #[allow(dead_code)]
    enum Baz {
        Baz1,
        Baz2,
    }
    
    struct Test {
        t: Option<usize>,
        b: Baz,
    }
    
    fn main() {
        use Baz::*;
        let x = Test { t: Some(0), b: Baz1 };
    
        match x {
            Test { t: Some(a), b: Baz1 } => unreachable!(),
            Test { t: None, .. } => unreachable!(),
            Test { .. } => unreachable!(),
    
        }
    }

**Comment by shahn** [comment]
This is the compiler output I get when running cargo test inside the clippy repository if I add a file tests/cyclomatic_complexity.rs with the content above:

cc = 0, arms = 1
Block { stmts: [Spanned { node: stmt(19: ), span: tests/cyclomatic_complexity.rs:16:9: 16:20 }, Spanned { node: stmt(21: let x = Test{t: Some(0), b: Baz1,};), span: tests/cyclomatic_complexity.rs:17:9: 17:46 }], expr: Some(expr(29: match x {
    Test { t: Some(a), b: Baz1 } => {
        {
            ::std::rt::begin_unwind("internal error: entered unreachable code",
                                    { &_FILE_LINE })
        }
    }
    Test { t: None, .. } => {
        {
            ::std::rt::begin_unwind("internal error: entered unreachable code",
                                    { &_FILE_LINE })
        }
    }
    Test { .. } => {
        {
            ::std::rt::begin_unwind("internal error: entered unreachable code",
                                    { &_FILE_LINE })
        }
    }
})), id: 18, rules: DefaultBlock, span: tests/cyclomatic_complexity.rs:15:15: 25:6 }
tests/cyclomatic_complexity.rs:15:5: 25:6
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'cc = 0, arms = 1', src/cyclomatic_complexity.rs:51

**Comment by Manishearth** [comment]
```
$ rustc panic.rs -L target/debug
cc = 0, arms = 1
Block { stmts: [Spanned { node: stmt(19: ), span: panic.rs:16:5: 16:16 }, Spanned { node: stmt(21: let x = Test{t: Some(0), b: Baz1,};), span: panic.rs:17:5: 17:42 }], expr: Some(expr(29: match x {
    Test { t: Some(a), b: Baz1 } => {
        {
            ::std::rt::begin_unwind("internal error: entered unreachable code",
                                    { &_FILE_LINE })
        }
    }
    Test { t: None, .. } => {
        {
            ::std::rt::begin_unwind("internal error: entered unreachable code",
                                    { &_FILE_LINE })
        }
    }
    Test { .. } => {
        {
            ::std::rt::begin_unwind("internal error: entered unreachable code",
                                    { &_FILE_LINE })
        }
    }
})), id: 18, rules: DefaultBlock, span: panic.rs:15:11: 25:2 }
panic.rs:15:1: 25:2
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'cc = 0, arms = 1', src/cyclomatic_complexity.rs:51
```


cc @oli-obk

**Comment by Manishearth** [comment]
Made it stop crashing via https://github.com/Manishearth/rust-clippy/commit/dc414e6c02cde7092b89cccd470a5b58fac736bd

**Comment by oli-obk** [comment]
oh... i never considered SEME code...
