### ISSUE TITLE
lint against using two function arguments whose name only differs in a underscore prefix

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#487]
in a function like `fn bla(i: i32, _i: i32) {}` the second argument's unused warning is silenced, but the naming of the second argument does not help in the documentation, because it has the same name as another argument. Also, in case the argument is used at some point, it needs a new name anyway, as you can't just remove the underscore.

**Comment by Manishearth** [comment]
:+1: 

To folks wanting to try this bug: This is pretty easy to write, just a `check_fn` `EarlyPass` lint (in `misc_early.rs`) which iterates through the argument list.

**Comment by GuillaumeGomez** [comment]
I take it if no one is on it then.

**Comment by Manishearth** [comment]
Go ahead!

**Comment by GuillaumeGomez** [comment]
Fixed.
