### ISSUE TITLE
Suggest String::new() instead of "".to_string() or "".to_owned()

### ISSUE THREAD

**Issue by leodasvacas** [Manishearth/rust-clippy#495]
`String::new()` seems like the idiomatic way of creating an empty string.

**Comment by birkenfeld** [comment]
I actually like `"".into()` since it's quite short :)

**Comment by llogiq** [comment]
Seconded.

**Comment by Manishearth** [comment]
I don't think there's any consensus on this. `to_string` and perhaps `into` are slower, but that's about it. I've actually seen `"".whatever()` more often than `String::new()`

**Comment by leodasvacas** [comment]
`"".` is just an ugly sequence of characters to me. But if there is no consesus then it shouldn't be a lint.
