### ISSUE TITLE
Suggest unwrap_or_default() instead of unwrap_or(default)

### ISSUE THREAD

**Issue by leodasvacas** [Manishearth/rust-clippy#496]
If `unwrap_or` is called with the default value, suggest `unwrap_or_default`. I think `unwrap_or_default()` is more elegant, however `unwrap_or("")` is an example where `unwrap_or` is shorter. Opinions?

**Comment by Manishearth** [comment]
`Allow` lint at least? I prefer `unwrap_or("")` as well. I think the other one is for more complex structs, perhaps?

**Comment by llogiq** [comment]
We could lint `unwrap_or(default())` though.
