### ISSUE TITLE
add another lint to bit_mask to warn on ineffective masks

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#53]
Currently, bad_bit_mask ignores masks that do not make the result of the whole expression constant, but don't add any value, e.g. `x|0` or `x & -1` or even `x | 1 > 2` (because the former are always equal to `x` and latter is equal to `x > 2` – they're not *wrong* per se, but may be misleading.

So let's have BitMask implement a second lint type (that is Warn instead of Deny), which I'd call `ineffective_bit_mask`.

**Comment by lfairy** [comment]
If we aren't already, we should warn about identity operations in general like `x * 1` or `0 + x`.

**Comment by llogiq** [comment]
That, too. So the lint should probably only warn about bit masks that are not by themselves identity operations, but which are rendered ineffective by the comparison.

Another "identity_op" lint should then check direct identity operations.

**Comment by llogiq** [comment]
Done.
