### ISSUE TITLE
Lint `<char literal> as u8`

### ISSUE THREAD

**Issue by fhartwig** [Manishearth/rust-clippy#563]
[This](https://internals.rust-lang.org/t/to-reduce-the-number-of-true-casts/3076) argues that the use of `as` casts should be minimised for safety reasons. One type of cast that can easily be avoided but is quite common in rust is casting from a char literal to `u8`. If the char literal is ascii, you can avoid the cast by using a byte literal (e.g. `b'a'`) instead, and if the char literal is non-ascii, the code is probably not doing what the author intended anyway [citation needed]. Therefore I suggest we lint all casts from char literals to `u8`, and suggest using byte literals instead.

**Comment by llogiq** [comment]
As usual, should have a macro check. Also we may lint truncating Unicode chars the same way we lint truncation in number types.

**Comment by fhartwig** [comment]
Yeah, this is basically as special case of the truncation lint. The important difference is that in this particular case, the cast can be trivially avoided.
