### ISSUE TITLE
Escape analysis and closure argument

### ISSUE THREAD

**Issue by sanxiyn** [Manishearth/rust-clippy#575]
I extended escape analysis to arguments in #523, which seemed reasonable. But when I added checking for `String` in addition to `Box`, I encountered the following case.

```rust
fn main() {
    let s = Some(String::from("string"));
    s.map_or(false, |s| s.contains(' '));
}
```

It seems wrong to warn closure argument to `map_or` on `Option<String>`, even if closure body would work with `&str`. One obvious idea is to skip escape analysis for closure argument. Any other idea?

**Comment by Manishearth** [comment]
I think we should just skip it for closures
