### ISSUE TITLE
Lint patterns like a && (a || b) which can be simplified

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#590]
Shamelessly grabbed from http://www.viva64.com/en/d/0320/ :smile:

**Comment by oli-obk** [comment]
We can do full simplification of the boolean expression and compare the results. That'll catch arbitrary cases of it.

**Comment by Manishearth** [comment]
Note that often you may write a boolean expression in a nonsimplified manner because that mirrors the intent. Not sure if this is an edge case or common though.
