### ISSUE TITLE
Lint bad comparisons of unsigned ints and 0

### ISSUE THREAD

**Issue by fhartwig** [Manishearth/rust-clippy#592]
As @scurest pointed out, we don't currently lint bad comparisons of unsigned integer types to 0. Specifically, I think we should lint `unsigned < 0`, which is always false and certainly not what the programmer intended, `unsigned <= 0` (which is weird and confusing and should be written as `== 0`) and `unsigned >= 0`, because it's a tautology and probably a bug as well.

**Comment by fhartwig** [comment]
@scurest It sounded like you have pretty much implemented this already. Want to make a PR?

**Comment by scurest** [comment]
`unsigned < 0` and `unsigned >= 0` are currently already caught by rustc with `warn(unused_comparisons)`. I guess I'll PR `unsigned <= 0`.

**Comment by fhartwig** [comment]
Ah, ok. I thought that `unsigned < 0` was already linted, but the lint wasn't triggered when I tried with `3u8 < 0`. Seems like it only warns if the non-zero operator is not a literal. Weird.

**Comment by llogiq** [comment]
BTW. This can be generalized to comparisons with `std::_::MIN`/`std::_::MAX`.

**Comment by scurest** [comment]
@llogiq But #592 just went through :o

You're right of course. I made a [branch](https://github.com/Manishearth/rust-clippy/compare/master...scurest:absurd-extreme-comparisons) to handle other integers and bools, but it's kind of rough (and doesn't pass dogfood). Would it be okay to PR it to get feedback?

**Comment by llogiq** [comment]
Of course! :smile:

**Comment by scurest** [comment]
Alright. Thanks.
