### ISSUE TITLE
string_to_string lint message confusing

### ISSUE THREAD

**Issue by fhahn** [Manishearth/rust-clippy#604]
Currently the `string_to_string` lint prints the following warning `'String.to_string()' is a no-op; use 'clone()' to make a copy`.

So for the following program, clippy will warn that both uses of `to_string()` are no-ops. But unless I misunderstand something, they are not no-ops. Because if you drop them (which should be OK if they really do nothing), the program won't compile, because `x`is already moved when it's used as the second argument.

So calling `to_string()` on a `String` in nightly creates a copy of the string using a formatter ([code](http://doc.rust-lang.org/src/collections/string.rs.html#225-227)), which is inefficient compared to `clone()`, but no no-op. It probably just suggest using `clone()` instead.

    #![feature(plugin)]
    #![plugin(clippy)]
    #![deny(clippy)]
    
    fn foo(_: String, _: String) {}

    fn main() {
        let x = "foo".to_owned();
        
        foo(x.to_string(), x.to_string());
    }

**Comment by mcarton** [comment]
This confused me too the first time I saw that.
