### ISSUE TITLE
Lint: Equal match arms

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#616]
If we have two equal non-empty match arms, they can be unified. E.g.

```
match foo {
    bla => bar(),
    blubb => bar(),
    _ => blob(),
}

// should be written as
match foo {
    bla | blubb => bar(),
    _ => blob(),
}
```

This is the same as #80, but with more statements to choose from – the difficulty will be to somehow order the match arms so that only potentially equal arms get compared, because comparing each arm would be in O(n²) for n match arms, which could get unwieldy.

**Comment by mcarton** [comment]
I’ve though of that for #603. I’m afraid only the *O(n²)* stopped me to implement that with the rest. Maybe we could define a hash function for expressions similar to how `is_exp_equal` is defined.

**Comment by llogiq** [comment]
Yep, either that or at least a PartialOrd so we can sort in O(n log n).

**Comment by mcarton** [comment]
We should also be careful that not all alike arms can be merged:
```rust
fn foo<T>(_: T) {}

fn main() {
    let a = Some(42);
    let b = Some("");

    match (a, b) {
        (Some(a), None) => foo(a),
        (None, Some(a)) => foo(a),
        _ => (),
    }
}
```
