### ISSUE TITLE
lint for more unstable functions: 

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#624]
iter.sum(), iter.product() – the former is usually equal to .fold(0, |acc, &i| acc + i), whereas the latter is equal to .fold(1, |prod, &i| prod * i). Need to check types, though.

**Comment by Manishearth** [comment]
Perhaps we should have a third lint group for stability lints?

**Comment by llogiq** [comment]
Makes sense.

**Comment by mcarton** [comment]
[These methods have been stabilized in `1.11.0`.](https://github.com/rust-lang/rust/pull/34530)
