### ISSUE TITLE
 lint comparison to bool (e.g. `y == true`)

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#630]
This is similar to our `needless_bool` lint, but for comparisons instead of `if`s.

**Comment by shssoichiro** [comment]
I took a shot at this one and submitted a PR.

**Comment by shssoichiro** [comment]
Question: Is there a case where this would get triggered and needless_bool would not?

**Comment by shssoichiro** [comment]
Can be closed with #645

**Comment by Manishearth** [comment]
#645
