### ISSUE TITLE
Warn when using debug formatting in user-facing output

### ISSUE THREAD

**Issue by killercup** [Manishearth/rust-clippy#634]
`format!` is the syntax extension used in `println!`, `panic!` and many other string formatting macros. It supports, among a lot of other cool stuff, two formatting modes: `Display` and `Debug` (optionally pretty-printed). This is described in the [fmt](http://doc.rust-lang.org/std/fmt/index.html) docs.

I propose a new lint which tries to warn when the Debug-mode (`{:?}` or `{:#?`}) is used in user-facing output.

Defining what 'user-facing' means is probably as much a challenge as writing the actual lint. At first, we could define it quite simple as: Everything that is _not_ in a test or a bench. Exceptions for logging macros could also be added.

Since this is only relevant to CLI applications, probably quite annoying when debugging, and could (at first) have many false-positives, I suggest making it Allow by default.

**Comment by mcarton** [comment]
It would be an interesting lint, there is already an *Allow* lint for using `print{,ln}!` (which is probably unwanted in libs). It might be complicated to check for though.

**Comment by killercup** [comment]
Oh, I didn't see that, @mcarton! The docs for `print_stdout` seem to be broken (it's below [precedence](https://github.com/Manishearth/rust-clippy/wiki#precedence) in the wiki but doesn't have a headline).

The lint proposed here would go one step further than `print_stdout` though, since you may want to `write!(f, "{}", data)` in a lib, but not `write!(f, "{:?}", data)`.

**Comment by mcarton** [comment]
> Oh, I didn't see that, @mcarton! The docs for `print_stdout` seem to be broken (it's below precedence in the wiki but doesn't have a headline).

Looks like it’s my fault, I just made a PR to fix the script and fixed the wiki.
