### ISSUE TITLE
lint on exported types that don't implement `Debug`

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#643]
should maybe wait for https://github.com/rust-lang/rfcs/pull/1422 so we can determine (without having to do a huge analysis) which types are (probably) exported over the crate boundary.

**Comment by killercup** [comment]
So like `missing-debug-implementations` (which is part of rustc) but only for items accessible from other crates?

**Comment by oli-obk** [comment]
oh, didn't know about that one. But still, it's not necessary for private types.

**Comment by llogiq** [comment]
IIRC this only lints visible types. Should we close this?

**Comment by mbrubeck** [comment]
The rustc lint is allow-by-default, and that seems unlikely to change. (Unlike clippy, rustc is very reluctant to enable lints with high false positive rates.)

I feel there would be some benefit to adding this lint to clippy, possibly along with some of the other allow-by-default lints from rustc.  Opt-in rustc lints have very low discoverability, and empirically very few people seem to use them in practice.  Making them warn-by-default in clippy would make them useful to a larger number of authors—in particular clippy users, who are already explicitly choosing to opt in to these types of "best practice" lints.

Yes, this would mean some duplication, but maybe there's a way that clippy could share code with the rustc lint, or even work by activating the built-in lint?

**Comment by flip1995** [comment]
> I feel there would be some benefit to adding this lint to clippy

I don't think, we should duplicate the lint code of rustc, so reimplementing them in Clippy is not an option IMO.

> Opt-in rustc lints have very low discoverability

The solution for this would be to better document the rustc lints somewhere.

> but maybe there's a way that clippy could share code with the rustc lint,

What we _could_ do is to create a `clippy::rustc` lint group, that contains all the allow-by-default rustc lints. But I don't really know how to do this and this probably will take some time to implement this (I guess some changes to rustc would also be necessary). One challenge I see for example is to collect the allow-by-default lints of rustc automatically, so we don't have to keep track of new rustc lints manually.
