### ISSUE TITLE
lint failed overflow checks

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#656]
lint operations in the form `a + b < a` (or b), which is likely a (failed) overflow check. In debug mode, the operation will panic on overflow. Suggest  `wrapping_add(..)`. Same with subtraction and underflow.

**Comment by martiansideofthemoon** [comment]
@Manishearth I would like to work on this bug. Could you explain what's happening here? What is the conditional `a + b < a` trying to check?

**Comment by mcarton** [comment]
`a + b < a` is a classic integer overflow check in C, but in Rust, it can panic and we have wrapping methods for that anyway.

**Comment by martiansideofthemoon** [comment]
@mcarton , which file would be the correct place to add this lint? So I need to detect `a + b < a` and suggest `a.wrapping_add(b) < a` ?

**Comment by mcarton** [comment]
No, Rust even have an [`overflowing_add`](https://doc.rust-lang.org/std/primitive.i32.html#method.overflowing_add) which returns the value and whether overflow has occurred. People testing for overflow should probably use that. Note that people have come up with a lot of ways to make that kind of checks in C, you might want to Google them to support more than one.
As for the file, it really does not matter, put it in a file which has similar lints if you can find one, or on its own file.

**Comment by Manishearth** [comment]
This needs to be a LateLintPass with checks ensuring that a, b, a are all integer types.
