### ISSUE TITLE
extend modulo_one lint with modulo_zero (because it also fails)

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#663]
Also who here knows whether/how modulo works with negative numbers? :smile:

**Comment by oli-obk** [comment]
negative numbers on which side of the operator?

**Comment by oli-obk** [comment]
Here's my relevant const-eval code (plus the two impls below that function): https://github.com/rust-lang/rust/pull/30587/files#diff-f442b936625c0bc4782fd6b386b17b6cR367

**Comment by oli-obk** [comment]
Note that `INT_MIN%-1` panics in rust, but mathematically it should be 0

**Comment by Mark-Simulacrum** [comment]
It appears that modulo zero is already checked by Rust: http://is.gd/Jj4zlg.
`warning: attempted remainder with a divisor of zero, #[warn(const_err)] on by default`

**Comment by martiansideofthemoon** [comment]
@llogiq , @Manishearth : Is this issue still valid? Would like to work on it!

**Comment by Manishearth** [comment]
Nope.

**Comment by mcarton** [comment]
@martiansideofthemoon but the are plenty of [other lints](https://github.com/Manishearth/rust-clippy/labels/E-easy) you can start with :smile:. Don’t hesitate to ask if you have any question.

**Comment by Manishearth** [comment]
Yeah, I offered him https://github.com/Manishearth/rust-clippy/issues/476 in IRC :smile:
