### ISSUE TITLE
for x in y { if x.something() { z }} should be for x in y.filter(|x| !x.something()) { z }

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#678]
encountered in the wild: https://github.com/Manishearth/rust-clippy/issues/600#issuecomment-184735383

``` rust
for x in y {
    if x.something() {
        operate_on(x);
    }
}
```

and

``` rust
for x in y {
    if !x.something() { continue }
    operate_on(x);
}
```

should be

``` rust
for x in y.filter(|x| x.something()) {
    operate_on(x);
}
```

**Comment by fhartwig** [comment]
This is too subjective to make it `Warn ` by default, in my opinion,.

**Comment by oli-obk** [comment]
> This is too subjective to make it Warn by default, in my opinion,.

allow is fine by me

**Comment by llogiq** [comment]
Yeah, it's less readable IMHO.

**Comment by mcarton** [comment]
I’m not sure I would want that by default either.

**Comment by killercup** [comment]
If we suggest

```rust
for x in y.iter().filter(…) {
    stuff(x);
}
```

we might as well suggest itertool's [foreach](http://bluss.github.io/rust-itertools/doc/itertools/trait.Itertools.html#method.foreach) because it reads nicer:

```rust
y.iter().filter(…).foreach(stuff);
```

(Another option would of course be to write

```rust
let y = y.iter().filter(…);
for x in &y {
   stuff(x);
}
```

but that just seems to split the logic.)

**Comment by llogiq** [comment]
A recent [thread](https://internals.rust-lang.org/t/zip-optimization-riddles/3189/) on internals suggests that different versions of zips that *should* do the same thing exhibit differing performance characteristics, so we should tread lightly here until they have this figured out.

I personally like `for` loops for *doing* stuff when no result is collected and using iterator methods when manipulating sequences or collections of data.

**Comment by oli-obk** [comment]
I agree that this is not a good idea.
