### ISSUE TITLE
Lint Yoda Conditions

### ISSUE THREAD

**Issue by killercup** [Manishearth/rust-clippy#695]
In some languages, it is easy to mistype conditions as assignments, especially in ones where it is common to assign variables in conditions (e.g. `if err == foo()` vs. `if err = foo()`). In these languages, some people choose to write comparisons in ‘Yoda form,’ i.e. `5 == x` instead of `x == 5`. Omitting the second `=` sign will break the first form with an error, but silently changes the meaning of the second one.

I don't think this is a risk in Rust, as assignments are of type `()` which cannot be interpreted as `bool`, and the only way to actually assign something in an `if` is to explicitly type `if let`.

While I have no personal preference, I think we should lint these comparisons for the sake of consistency (maybe as Allow by default?).

Bonus: [Here](http://eslint.org/docs/rules/yoda) is ESLint's _yoda_ rule.

**Comment by Manishearth** [comment]
Note that `==` isn't commutative due to deref coercions, so there are legitimate times you may want to do `foo() == err`, i.e. when `foo()` needs dereferencing.

**Comment by killercup** [comment]
Oh, interesting! I didn't think of that! That makes this a bit useless as the only goal was (stylistic) consistency. (Feel free to close this.)
