### ISSUE TITLE
useless_format should only warn for String

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#697]
It currently warns for `format!("{}", e);` where `e` is anything implementing `Show`.

cc @mcarton

**Comment by oli-obk** [comment]
The warning is correct imo, `e.to_string()` is much more obvious. So only the hint should be adjusted.

**Comment by mcarton** [comment]
`Show` hasn’t been a thing for a long time now (in Rust history) :p

I that case I like `e.to_string()` better, no?

**Comment by Manishearth** [comment]
Using format in lieu of `.to_string()` is a common pattern, though.

**Comment by mcarton** [comment]
They are equivalent anyway as the trait implementation is `impl<T> ToString for T where T: Display + ?Sized` so ok, I’ll limit it to `String` and `&str`.

**Comment by llogiq** [comment]
I still think `.to_string()` is more readable. Maybe re-add it as an `allow`ed lint?
