### ISSUE TITLE
Lint `fn new() -> Self` without Default

### ISSUE THREAD

**Issue by mcarton** [Manishearth/rust-clippy#705]
@vi just suggested to have a lint “for having `fn new() -> Self`, but not having `Default`” on IRC.
That’s probably a good idea, but it might trigger *a lot*, so maybe an Allow lint by default?

**Comment by Manishearth** [comment]
Not sure if it needs to be `Allow`, but sure :)

**Comment by llogiq** [comment]
I'd be OK with `warn`, too.
