### ISSUE TITLE
Suggest '.values_mut()' if `HashMap` mutably borrowed

### ISSUE THREAD

**Issue by frewsxcv** [Manishearth/rust-clippy#709]
If one uses:

``` rust
for (_, layer) in &mut self.layers {
    ...
}
```

clippy currently suggests to use `HashMap::values`. Since there is no `HashMap::values_mut`, there's no way to replicate this same functionality with a method, so it shouldn't be suggested.

**Comment by oli-obk** [comment]
there is a `values_mut` on `HashMap` since 1.10: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.values_mut
