### ISSUE TITLE
lint internally mutable keys in maps

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#729]
I'm not sure if this is actually possible, but it is a logic error to change keys in hashmaps or btreemaps. So if we can identify common types with interior mutability, we could warn when finding those types as keys in a map.

**Comment by fhartwig** [comment]
It looks like the Cell types don't implement `Ord` or `Hash`, so it's probably quite difficult to accidentally use them in a key for any of the Map types.

**Comment by llogiq** [comment]
Yeah, I think #732 will suffice to ensure this, and is more to the point. Closing this.
