### ISSUE TITLE
does not compile on rust stable?

### ISSUE THREAD

**Issue by buster** [Manishearth/rust-clippy#73]
When i want to use this i get the following error:

```
clippy-0.0.4/src/bit_mask.rs:153:32: 153:80 error: this function takes 2 parameters but 3 parameters were supplied [E0061]
clippy-0.0.4/src/bit_mask.rs:153             .and_then(|def_id| lookup_const_by_id(cx.tcx, def_id, Option::None))


```

**Comment by Manishearth** [comment]
Plugins can't work on Rust stable, sorry.

I'm going to trigger a build on master to see if it still works with nightly (plugins are very fast moving)

**Comment by Manishearth** [comment]
[It passes](https://travis-ci.org/Manishearth/rust-clippy) with the current nightly.

You can still try it out by using nightly and compiling your program. A tool like [multirust](https://github.com/brson/multirust) should work for switching toolchains easily.

**Comment by AndroidOatmeal** [comment]
Thanks for the update here. I'm a rust newbie as well and ran into the same issue, not knowing plugins can't work on Rust stable. Perhaps it might be helpful to others to mention this in the readme?

**Comment by Manishearth** [comment]
done https://github.com/Manishearth/rust-clippy/commit/240d9716d89df4dcf7247b6fa6a6b1976ef78fb2
