### ISSUE TITLE
lint calling methods on negative literals

### ISSUE THREAD

**Issue by durka** [Manishearth/rust-clippy#748]
Prevent rust-lang/rust#32109 (`-15.6f64.floor()` is `-(15.6f64.floor())`).

**Comment by llogiq** [comment]
Don't our precedence lint already catch that?

**Comment by mcarton** [comment]
[It does.](https://github.com/Manishearth/rust-clippy/blob/08b7931b6b7e7022c2c7d08dc950a8dd93bf70ac/tests/compile-fail/precedence.rs#L16-L25)
