### ISSUE TITLE
Transmuting between T and *T

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#749]
An easy mistake to make, especially when T is a function pointer

https://github.com/rust-lang/rust/pull/31710#issuecomment-193554820

**Comment by cramertj** [comment]
This was completed in #797

**Comment by mcarton** [comment]
@cramertj Thanks for helping cleaning this up. FYI, when you make a PR, if you put « Fix #749 » in the description, the issue will close automatically when the PR is merged.

**Comment by cramertj** [comment]
Good to know. Thanks.
