### ISSUE TITLE
collapsible if statements

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#75]
`if x { if y { ... } }` can be written as `if x && y { ...}`.

**Comment by llogiq** [comment]
To clarify, both if-expressions may not have an else-clause, and the inner if-expression must be the only expr inside thr outer one.

I believe this is something that usually comes up in the heat of refactoring...

**Comment by Manishearth** [comment]
Fixed in #76

**Comment by JorisDeRidder** [comment]
Collapsing consecutive if-statements `if x { if y { ... } }` into `if x && y { ... }` might not be justified if `y` depends on `x`. For example if `a` is an array of size 10, then `if n<10 { if a[n] < 3 { ... } }` should probably not be collapsed into `if n<10 && a[n]<3 { ... } ` as `a[n]` is evaluated even if `n>10`, causing a panic.

**Comment by y21** [comment]
> [...] not be collapsed into `if n<10 && a[n]<3 { ... }`  as `a[n]` is evaluated even if `n>10`, causing a panic.

That doesn't sound right to me? [`&&` short circuits](https://doc.rust-lang.org/book/appendix-02-operators.html#operators), so the rhs is only evaluated iff lhs is true. If `n<10` is not true, then no panic can occur as `a[n]` is not evaluated
```rs
if false && { println!("RHS"); true } {}
```
This does not print anything and shows the short circuit behavior (`&` on the other hand always evaluates the right hand side)

**Comment by JorisDeRidder** [comment]
Ah yes, forgot about the short-circuiting in Rust. Sorry about the noise.

**Comment by timorl** [comment]
I don't think this is really noise, the fact that one of `&` and `&&` short-circuits and the other doesn't means it's a pretty reasonable preference to have nested `if`s whenever you want to make sure the second statement doesn't get executed.  Trying to always catch whether someone is using the correct number of `&` and `|` seems unnecessarily risky.
