### ISSUE TITLE
Lint against indexing and slicing

### ISSUE THREAD

**Issue by aochagavia** [Manishearth/rust-clippy#755]
Some projects (e.g. operating systems) need to be very careful about panics. Since indexing and slicing panic when indices are out of bounds, I think it would be useful to have a lint for that (allowed by default).

Does this fit the scope of clippy?

**Comment by oli-obk** [comment]
This would be one of the "restrictions" mentioned in #632 

Hard to do cross crate though

**Comment by Manishearth** [comment]
THis goes under the "restrictions" thing. Completely avoiding panics is global thing, and hard to do, but blacklisting certain operations is a good step.

**Comment by aochagavia** [comment]
Does the "restrictions" thing require refactoring of clippy or could this particular lint be implemented without major changes?

**Comment by Manishearth** [comment]
It requires refactoring of the lint groups machinery in the python script to be able to create more non-pedantic Allow groups.

**Comment by aochagavia** [comment]
Hmmm... I am not familiar with the architecture of clippy, so I guess I would rather wait until those changes are in place before implementing this.

**Comment by Manishearth** [comment]
Feel free to implement this as a regular pedantic `Allow` lint.

**Comment by aochagavia** [comment]
Ok!
