### ISSUE TITLE
Support disabling clippy on certain modules

### ISSUE THREAD

**Issue by ihrwein** [Manishearth/rust-clippy#785]
First of all, thanks for this great library!

I've a generated module (by peg-rs) which contains some lint warnings. I'd like to disable the linting
on that module, as it's generated.

**Comment by llogiq** [comment]
You could simply `#[allow(clippy)]` on that module.

**Comment by ihrwein** [comment]
It works like a charm, thanks for your quick help!

**Comment by llogiq** [comment]
You're welcome.
