### ISSUE TITLE
lint recursive enums

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#787]
Those recently led to OOM in rustc nightly.

Basically lint enum variants containing fields of the same enum type, but stop checking within known pointer classes (box, syntax::ptr::P, ...)

**Comment by mcarton** [comment]
Aren’t those forbidden anyway?
```rust
% cat a.rs
enum Foo {
    A,
    B(Foo),
}
% rustc a.rs
error: main function not found
a.rs:1:1: 4:2 error: recursive type `Foo` has infinite size [E0072]
a.rs:1 enum Foo {
a.rs:2     A,
a.rs:3     B(Foo),
a.rs:4 }
a.rs:1:1: 4:2 help: run `rustc --explain E0072` to see a detailed explanation
a.rs:1:1: 4:2 help: insert indirection (e.g., a `Box`, `Rc`, or `&`) at some point to make `Foo` representable
error: aborting due to previous error
```

**Comment by llogiq** [comment]
Ah, the problem was that the rustic lint runs after type checking... I was a bit confused because of [Rust #32326](https://github.com/rust-lang/rust/issues/32326).
