### ISSUE TITLE
to_string is perhaps more idiomatic

### ISSUE THREAD

**Issue by hoodie** [Manishearth/rust-clippy#788]
Currently there is https://github.com/Manishearth/rust-clippy/wiki#str_to_string and it tells you that `to_string()` is slow. Should a lint warn people about this? As soon as specializations lands there will be no difference and you could argue that &str.to_owned() is not idiomatic, so there might be a lint that contradicts an earlier lint.

What do you think?

**Comment by mcarton** [comment]
> As soon as specializations lands

Isn’t it the case already? (since a few days, in nightly and modulo an actual specialization of `str::to_string` :sweat_smile: )
We should probably deprecate that lint yes. Ref #728 and #743.

**Comment by llogiq** [comment]
Not everyone – even those using clippy – develops against nightly.

Also I don't consider neither `.to_string()` nor `.to_owned()` un-idiomatic. Still, I agree we should deprecate that lint.
