### ISSUE TITLE
nonminimal_bool has pathological behavior for large strings of or'd boolean expressions

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#825]
It's exponential in the amount of time it takes. With eight checks it takes 0.2 seconds, for 9 it takes 0.8, and for 10 it takes 20. I haven't tested above this, but the following seems to take forever:

```rust
fn rust_type_id(name: String) {
    if "bool" == &name[..] ||
        "uint" == &name[..] ||
        "u8" == &name[..] ||
        "u16" == &name[..] ||
        "u32" == &name[..] ||
        "f32" == &name[..] ||
        "f64" == &name[..] ||
        "i8" == &name[..] ||
        "i16" == &name[..] ||
        "i32" == &name[..] ||
        "i64" == &name[..] ||
        "Self" == &name[..] ||
        "str" == &name[..] {
        unreachable!();
    }
}
```

cc @oli-obk 

I'm going to publish a quick-fix that ignores such large things, but there probably is a better fix for this. I don't understand QMC enough to fix it though.

**Comment by Manishearth** [comment]
FWIW this was found in rust-bindgen. If you want to see this behavior in bindgen without needing a clang clone, remove the build script and build the `--lib`.

**Comment by oli-obk** [comment]
well that specific case should be a match anyway imo, but yea, it's exponential in memory and time

Your fix looks perfectly reasonable to me.

**Comment by Manishearth** [comment]
ok then, thanks!
