### ISSUE TITLE
Lint missing lints in LintPasses

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#831]
If we miss a Lint in the `lint_array!` of the `*LintPass`, we will get strange and confusing behavior (like lint warnings + `unknown_lint`).

This requires walking the call graph and recording any lint symbol on the way. Then checking the `get_lints` method if all recorded lints are present.

Note that this would be the first lint that is specifically aimed at helping write lints.

**Comment by oli-obk** [comment]
Make sure to take a [Totem](http://inception.wikia.com/wiki/Totem) with you.

**Comment by llogiq** [comment]
We don't need to follow the call graph, just identify the reachable functions for any LintPass implementation. The naive set-based algorithm should work nicely.

**Comment by mcarton** [comment]
Closed by #1207.
