### ISSUE TITLE
#[warn(doc_markdown)] asking me to put "32MiB" into ticks

### ISSUE THREAD

**Issue by Evrey** [Manishearth/rust-clippy#835]
> warning: "you should put `32MiB` between ticks in the documentation, #[warn(doc_markdown)] on by default"

My 98th commit having this issue:

[Evrey/GBArs - 917d67ab6daad275760826db6a0f3e4680ca5c0c](https://github.com/Evrey/GBArs/tree/917d67ab6daad275760826db6a0f3e4680ca5c0c)

[File and Line](https://github.com/Evrey/GBArs/blob/917d67ab6daad275760826db6a0f3e4680ca5c0c/src/hardware/gamepak.rs#L34)

So, what's happening there? Looks like clippy thinks that 32MiB would be some kind of code expression or identifier or whatever.

**Comment by mcarton** [comment]
Yes, it thinks “32MiB” is a camel-cased identifier. It would be pretty easy to fix but I’m not sure what the better solution would be:

- white-list those units (at least `{k,M,G,T,P}iB`), `{k,M,G,T,P}B` and `{k,M,G,T,P}b` should already be ok;
- ignore stuff with a number in it (or at least starting with a number) but then `32 MiB` would still warn;
- force idents to be paths with `::` (this would lead to very few false positives, but would ignore most cases I think).

**Comment by Evrey** [comment]
I think that whitelisting would be the best solution, at least for those common cases and on demand some SI units. However, this also smells like a little bug in clippy, as "stuff starting with a digit" isn't a valid identifier in Rust.

So...

- "32MiB" has no lint because it isn't a valid identifier.
- "32 MiB" catches the whitelisted identifier "MiB".

**Comment by mcarton** [comment]
> Btw.: A lower case `k` is legacy, upper case `K` is correct.

No it’s not. `K` is the symbol for the kelvin, the SI unit of temperature.

> And `E` could be included as well, as it is within a 64-bit integer type's range.

Will do.

**Comment by Evrey** [comment]
> The first letter of each such prefix is therefore identical to the corresponding SI prefixes, except for "K", which is used interchangeably with "k", whereas in SI, only the lower-case k represents 1000.

[src](https://en.wikipedia.org/wiki/Binary_prefix#kibi) - Referenced document is a dead link, though.

Small "k" is still valid though. And yes, in the world of physics, upper case "K" is invalid.
