### ISSUE TITLE
cargo build err

### ISSUE THREAD

**Issue by menshibin** [Manishearth/rust-clippy#837]
booleans.rs:60 64 
expected one of `.`, `;`, `}`, or an operator, found `?`

**Comment by llogiq** [comment]
Could you please give us versions of Rust, cargo and clippy as well as the command line to compile?

**Comment by mcarton** [comment]
>  expected one of `.`, `;`, `}`, or an operator, found `?`

The operator `?` has been merged on 2016/02/29, so you probably just need to update your ancient nightly version of *rustc* :smile:

**Comment by Kerosene2000** [comment]
```bash
multirust update nightly
multirust run nightly cargo install clippy
```
😄
