### ISSUE TITLE
new_without_default warning for builder pattern

### ISSUE THREAD

**Issue by Jascha-N** [Manishearth/rust-clippy#839]
Should builders with no required arguments really implement `Default`? I mean, it is possible, but since they are purely utility types, it seems pretty pointless to have them implement any traits other than maybe `Debug`. What do you think?

**Comment by mcarton** [comment]
Yes, but how would Clippy know a type is just a builder and does it make any harm for a builder to be `Default`?

**Comment by llogiq** [comment]
@mcarton Perhaps look at the type name and see if it ends in`Builder`?
