### ISSUE TITLE
lint `mem::forget(_)`, it's likely to cause memory leaks

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#858]
This one should be `allow`, obviously. :smile:

**Comment by cramertj** [comment]
I can take this one. Should there be a suggested alternative or an explanation for the lint other than "usage is likely to cause memory leaks"?

**Comment by Manishearth** [comment]
Sure. Nah, just that it can leak. There's no general fix; when you need it you need it.
