### ISSUE TITLE
Warn on re-implementing PartialEq::ne

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#86]
The `ne` method has a good known-correct default implementation. Overriding it is likely to have no particular benefit while any manual implementation may fail to respect the strict inverse rule.

Note that this only applies to items implementing Eq, as PartialEq items don't need to respect the strict inverse rule, e.g. f64::NAN will return `false` on both `eq` and `ne` in any event.

Note that this does not even need type lookup, as we have all required information directly on the trait impl.

**Comment by tbu-** [comment]
`f64::NAN` will always return `false` on `eq` and `true ` on `ne`.

**Comment by llogiq** [comment]
Thanks for clearing up my error. So there is even less of a case for `ne` to be anything other than the default.

**Comment by clarcharr** [comment]
@llogiq should this be linting for the `PartialEq` definitions in the standard library too? These override the existing `ne` impls for better short-circuiting, but I'm not sure if it's necessary even for performance.

**Comment by llogiq** [comment]
I don't worry about the standard library at all in this case.

Actually there may be good reason for the impls. LLVM is a strange beast sometimes. I certainly wouldn't remove the impls without prior careful measurement. That said, the standard library can add `#[allow(..)]`s, too, just like everyone else.
