### ISSUE TITLE
#[allow(transmute_ptr_to_ref)] doesn't silence warning

### ISSUE THREAD

**Issue by agrover** [Manishearth/rust-clippy#864]
cc @mcarton 

I'm transmuting to a ref of a different type:

https://github.com/agrover/devicemapper-rs/blob/master/src/lib.rs#L367

so I'm not sure the lint hint (use `&*`) is applicable... but in any case I don't seem to be able to disable the lint by using allow().

**Comment by mcarton** [comment]
Weird. As far as I can tell the lint is declared properly and the error is created the same way as any other. *rustc* itself decides whether to display the error or not from the span. Also the error is hidden with `#![allow(…)]`.

@Manishearth problem in *rustc*?

> I'm transmuting to a ref of a different type […] so I'm not sure the lint hint (use &*) is applicable...

Raw pointer casts have some sanity checking `transmute` do not have, so it’s better to used them when possible.

**Comment by Manishearth** [comment]
Not sure, could be a bug, though the rustc code is  simple enough.

**Comment by birkenfeld** [comment]
@agrover where are you putting the `#[allow]` annotation?

**Comment by agrover** [comment]
errm...can't repro. User error? :smile: closing.
