### ISSUE TITLE
Better reporting on single_match

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#87]
Currently, single_match produces the following `span_note` (from the README):

src/main.rs:8:5: 11:6 note: Try if let Some(y) = x { ... }
src/main.rs:8     match x {
src/main.rs:9         Some(y) => println!("{:?}", y),
src/main.rs:10         _ => ()
src/main.rs:11     }

It would be possible with judicious use of `span_to_snippet` to produce the following `note` (without span):

```
src/main.rs:8:5: 11:6 note: Try 
if let Some(y) = x { 
    println!("{:?}", y)
}
```

This would remove the duplication from the warning that is always shown above, and make the note much more useful, as the user could basically just copy the code.

**Comment by Manishearth** [comment]
Fixed in https://github.com/Manishearth/rust-clippy/pull/127
