### ISSUE TITLE
bad_bit_mask check is broken

### ISSUE THREAD

**Issue by koute** [Manishearth/rust-clippy#88]
Consider the following code:

    let a = 0u8;
    println!( "{}", (a & 0b10000000) == 0 );

for which clippy spews out an error:

    test.rs:4:21: 35:42 error: incompatible bit mask: _ & 128 can never be equal to 0, #[deny(bad_bit_mask)] on by default
    test.rs:4     println!( "{}", (a & 0b10000000) == 0 );

The expression `(0 & 0b10000000) == 0` is obviously `true`, so this lint is clearly broken here.

**Comment by Manishearth** [comment]
cc @llogiq

**Comment by llogiq** [comment]
I've seen it. And yes, it's a real error.

**Comment by llogiq** [comment]
And it's fixed.
