### ISSUE TITLE
Scattered extern-crate/use/mod/… statements

### ISSUE THREAD

**Issue by regexident** [Manishearth/rust-clippy#880]
In addition to https://github.com/Manishearth/rust-clippy/issues/879 I'd love to have a lint that enforces my header statements (`extern crate …`, `mod …`, `use …`, …) to be cleanly grouped.

So that this would trigger a warning:
```rust
mod …;

use std::…;

mod …;
```

While this wouldn't:

```rust
mod …;
mod …;

use std::…;
```

Nor would this:

```rust
use std::…;

mod …;
mod …;
```

Bonus points for warning on missing/excessive newlines between groups.

**Comment by regexident** [comment]
This is would probably be a candidate for `pedantic`.

**Comment by regexident** [comment]
Probably another candidate for [rustfmt](https://github.com/rust-lang-nursery/rustfmt/). Oh well. Sorry for spamming (#879, #880, #881). 😇 😞

**Comment by llogiq** [comment]
No problem. We're just pushing back because we think your time is better spent with other lints. :smile:

**Comment by regexident** [comment]
😘 

---

So this is you offering to help get #879 integrated into rustfmt asap, to get me back to work on clippy lints? How generous of you. 😈 😇
