### ISSUE TITLE
Unsorted extern-crate/use/mod/… statements

### ISSUE THREAD

**Issue by regexident** [Manishearth/rust-clippy#881]
In addition (or as alternative) to https://github.com/Manishearth/rust-clippy/issues/880 I'd love to have a lint that warns on mal-sorted use statements inside a group.

So that this would trigger a warning:

```rust
use lorem::ipsum::{dolor, sit, amet};
use consectetur;
use adipiscing::elit;
```

while this wouldn't:

```rust
use adipiscing::elit;
use consectetur;
use lorem::ipsum::{amet, dolor, sit};
```

This is would probably be a candidate for `pedantic`.

**Comment by llogiq** [comment]
Again, this is very opinionated and probably more suited to rustfmt.

**Comment by regexident** [comment]
Fair point. And there appears to be an issue for it already: https://github.com/rust-lang-nursery/rustfmt/issues/298.
