### ISSUE TITLE
Lint basic arithmetic on integers or floating point arithmetic

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#887]
This would be an allow lint that could be activated for code where a more specific kind of arithmetic is wanted (e.g. wrapping or checked).

Courtesy of tomaka on reddit

**Comment by mcarton** [comment]
We could also lint floating point arithmetic. See [RFC: Float-free libcore ](https://github.com/rust-lang/rfcs/pull/1596)https://github.com/rust-lang/rfcs/pull/1596.

**Comment by llogiq** [comment]
Sure, the more the merrier :smile:
