### ISSUE TITLE
allow similar names

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#888]
In miri, there was another instance where an assignment was evaluated on `lvalue, rvalue`. Those are the usual jargon in interpreters, so we should at least whitelist them.

I think we should discuss whether this lint should really warn by default. It seems plenty opinionated to me.

**Comment by oli-obk** [comment]
It seemed pretty straight forward to lint on names that only differ in a single character, but in practice this lint has been too verbose with all the `lty` vs `rty` and `lvalue` vs `rvalue` and others.

Our whitelist currently contains:

* `parsed` vs `parser`
* `lhs` vs `rhs`
* `tx` vs `rx`
* `set` vs `get`

Legitimate `allows` for the lint:

* https://github.com/japaric/stats.rs/blob/50962bd6ca25de814a3b2e5f465641ac3736a482/src/univariate/outliers/tukey.rs#L69-L94
* https://github.com/jfager/d3cap/blob/0dce02a6b6ef4884cb2ce26a21131fa3a3d6796b/src/d3cap/d3cap.rs#L482-L483
* https://github.com/brunodea/gebemula/blob/8eb25b7bac819238d8d48cf0d9ea5495eec2dd52/src/main.rs#L8
* https://github.com/japaric/stats.rs/blob/50962bd6ca25de814a3b2e5f465641ac3736a482/src/bivariate/regression.rs#L65-L92
* https://github.com/SAPikachu/euphonium/blob/40d031509f7b3d20d4911d2335ed7c42522bd4b0/src/serve.rs#L62
* https://github.com/maidsafe/safe_vault/blob/ccbca0173353042d0bf348005224a31694f76e42/src/lib.rs#L49


* In unit tests:
   * https://github.com/ethcore/parity/blob/f9f11b6f74179cad6774bcec8d2767134d6afa9f/ethcore/src/chainfilter/indexer.rs#L90
   * 4 cases in https://github.com/ethcore/parity/tree/f9f11b6f74179cad6774bcec8d2767134d6afa9f/util
   * https://github.com/jgallagher/rusqlite/blob/254a0b4cd84369261069a28c628fe13c17be3bc5/src/transaction.rs
   * https://github.com/ethcore/parity/blob/bdb35cfaed368191b68e1134cb38078738d90e54/util/src/journaldb/refcounteddb.rs
   * https://github.com/ethcore/parity/blob/bdb35cfaed368191b68e1134cb38078738d90e54/util/src/journaldb/archivedb.rs#L181

Dubious `allows` (allowing lots of clippy lints):

* https://github.com/bfops/playform
* https://github.com/Luthaf/cymbalum/blob/dd741aafd09873b780dbe407645c274cf3452935/src/lib.rs

Dubious `allows` (more expressive names would probably be great):
* https://github.com/stevenpack/koala-dns/blob/9d0af71f0515a493d27e8789964a5163c731ac28/src/dns/message.rs#L118

Unnecessary `allows` (early version were too verbose):
* https://github.com/SAPikachu/euphonium/blob/e2aa671f04f57e250a58a6cc01600a8bdbb53803/src/resolver.rs#L116

Unnecessary `allows` (refactoring lost the need?):
* https://github.com/SAPikachu/euphonium/blob/e2aa671f04f57e250a58a6cc01600a8bdbb53803/src/resolver.rs#L153
* https://github.com/stevenpack/koala-dns/blob/9d0af71f0515a493d27e8789964a5163c731ac28/src/dns/message.rs#L99

**list not complete, still updating**

Preliminary conclusion: make sure it doesn't trigger in tests and make it allow-by-default
