### ISSUE TITLE
needless_borrow not in wiki

### ISSUE THREAD

**Issue by waywardmonkeys** [Manishearth/rust-clippy#912]
I got a warning from Clippy about a `needless_borrow` but it isn't covered in the wiki.

**Comment by oli-obk** [comment]
it's in this list: https://github.com/Manishearth/rust-clippy#lints not sure how frequently the wiki is updated.

**Comment by mcarton** [comment]
[Fixed](https://github.com/Manishearth/rust-clippy/wiki#needless_borrow), sorry for the inconvenience.
Ping #569.
