### ISSUE TITLE
Error using Rust 1.10.0-nightly

### ISSUE THREAD

**Issue by cristianoliveira** [Manishearth/rust-clippy#918]
I am getting the follow error using the nightly version:
```bach
error: method `build_controller` has 3 parameters but the declaration in trait `rustc_driver::CompilerCalls::build_controller` has 2 [E0050]
src/lib.rs:62     fn build_controller(&mut self, sess: &Session, matches: &getopts::Matches) -> driver::CompileController<'a> {
src/lib.rs:63         let mut control = self.0.build_controller(sess, matches);
src/lib.rs:64
src/lib.rs:65         let old = std::mem::replace(&mut control.after_parse.callback, box |_| {});
src/lib.rs:66         control.after_parse.callback = Box::new(move |state| {
src/lib.rs:67             {
```

**Comment by mcarton** [comment]
How recent is your nightly? It compiles fine on Travis with *rustc 1.10.0-nightly (e0fd34bba 2016-05-09)* which is the last nightly.

**Comment by cristianoliveira** [comment]
I am using `rustc 1.10.0-nightly (8da2bcac5 2016-04-28)`. Let me update it to see if it works

**Comment by cristianoliveira** [comment]
Updating to `rustc 1.10.0-nightly (e0fd34bba 2016-05-09)` it builds. But for some reason running the tests it does not download the `lazy_static`:

I noticed that it works on Travis where runs using linux:  
```bash 
Using worker: worker-linux-docker-3f346bb8.prod.travis-ci.org:travis-linux-10

...

cargo test --features debugging
 Downloading regex v0.1.69
 Downloading compiletest_rs v0.1.1
 Downloading lazy_static v0.1.16
 Downloading aho-corasick v0.5.2
 Downloading thread_local v0.2.5

...
```

My current env:
OS X 10.11 El Capitan
Rust: 1.10.0-nightly (e0fd34bba 2016-05-09)
Cargo:  0.11.0-nightly (d6e1726 2016-05-08)

I know it will put some extra time on CI but we can add OS X  in the travis script. What do you think guys?

It is pretty simple: 
https://github.com/cristianoliveira/funzzy/blob/master/.travis.yml

**Comment by oli-obk** [comment]
> But for some reason running the tests it does not download the lazy_static:

could you run `cargo update` and show the output of `cargo test`?

**Comment by cristianoliveira** [comment]
> could you run cargo update and show the output of cargo test?
I did and got same error :/

```bash
tests/run-pass/mut_mut_macro.rs:5:1: 5:26 note: crate name: lazy_static
tests/run-pass/mut_mut_macro.rs:5:1: 5:26 error: can't find crate for `lazy_static` [E0463]
tests/run-pass/mut_mut_macro.rs:5 extern crate lazy_static;
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors

------------------------------------------
```

**Comment by oli-obk** [comment]
is that the full output? it says `2 previous errors`.

`cargo clean` won't fix this specific one, but I've had it fix problems before, due to different compiled crates in the target folder

**Comment by cristianoliveira** [comment]
`cargo clean` works :D

I will close it and open another issue to talk about my previous suggestion.

**Comment by llogiq** [comment]
I got the same error when updating rust, however just calling `cargo clean; cargo test` solved the problem for me. Perhaps some intermittent network problem?
