### ISSUE TITLE
Clippy exits immediately on Windows

### ISSUE THREAD

**Issue by peschkaj** [Manishearth/rust-clippy#923]
Running `cargo-clippy.exe` produces no output or failure message.
Running `cargo clippy` informs me that `error: third party subcommand `cargo-clippy.exe` exited unsuccessfully`

System is Windows 10 Pro (10.0.10586 N/A Build 10586)
Using `rustc 1.10.0-nightly (e0fd34bba 2016-05-09)` as the default, and installing clippy with `cargo install clippy`.

**Comment by oli-obk** [comment]
are you using rustup or multirust?

I just tried it with rustup, and I'm getting a `librustc_driver-.......dll not found`. Probably rustup not setting some vars

**Comment by oli-obk** [comment]
Ah this is being fixed here: https://github.com/rust-lang-nursery/rustup.rs/pull/402

**Comment by peschkaj** [comment]
Confirming it's rustup - I've got limited internets, but will keep checking in.

**Comment by CryZe** [comment]
Looks like rustup 0.2 fixed this :)

**Comment by mcarton** [comment]
Cool :smile:
