### ISSUE TITLE
cargo install clippy 0.0.67  complie error

### ISSUE THREAD

**Issue by huwsun** [Manishearth/rust-clippy#925]
On my mac os x,cargo install clippy output error:
 
  Compiling clippy v0.0.67
error: wrong number of lifetime parameters: expected 1, found 3 [--explain E0107]
   --> /Users/polus/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/cyclomatic_complexity.rs:125:14
125 |>     tcx: &'a ty::TyCtxt<'a, 'gcx, 'tcx>,
    |>              ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: wrong number of lifetime parameters: expected 1, found 3 [--explain E0107]
  --> /Users/polus/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/escape.rs:43:10
43 |>     tcx: ty::TyCtxt<'a, 'tcx, 'tcx>,
   |>          ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by oli-obk** [comment]
you need to update your rust nightly
