### ISSUE TITLE
type monstrosity check

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#93]
We can match `Ty`s above a certain depth or size (either span length or tree node count) and suggest breaking them into multiple `type` definitions.

The matching would actually be fairly easy (need to be careful w/ stack though), but the suggestion could be arbitrarily clever, e.g. searching for duplicate parts.

**Comment by Manishearth** [comment]
Note that we should only do this in specific cases. typedefs, for example, should not be linted.


Alternatively, we can use `check_ty` and use `get_parent()` to ensure we're not in a typedef. But `get_parent` is a bit iffy in how it works (nrc is working on fixing ast_map parenting) so it may not work. Could try though.

**Comment by llogiq** [comment]
Perhaps we could still check typedefs, but report only if they contain significant duplication.

I trust that `get_parent` will only improve in the future. :smile:

**Comment by llogiq** [comment]
Apart from the get_parent approach, we could also just check exprs, items (`ItemTy`s get special treatment), trait_items (`TypeTraitItem`s get special treatment), and impl_items (`TypeImplItem`s get special treatment) for monstrosities. This would effectively remove the `get_parent` reliance.
