### ISSUE TITLE
Bad error running `cargo clippy` on multiple crate project

### ISSUE THREAD

**Issue by brson** [Manishearth/rust-clippy#935]
When I run this on rustup.rs I see:

```
brian@ip-10-234-25-118:~/dev/rustup.rs⟫ cargo clippy
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
thread '<main>' panicked at 'cargo rustc failed', /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lib.rs:131
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error:
```

cargo 0.11.0-nightly (5cb2bb1 2016-05-14)

rustc 1.10.0-nightly (5ebe41835 2016-05-15)

clippy 0.0.67

**Comment by Manishearth** [comment]
Yeah, `cargo rustc` doesn't allow you to run on all packages like `cargo build`. I'd prefer if Cargo upstream fixed this by changing the default or adding a "cargo rustc --all-targets" thing

**Comment by brson** [comment]
Another similarly ugly error:

```
101 brian@ip-10-234-25-118:~/dev/rustup.rs⟫ cargo clippy --bin blah
error: no bin target named `blah`
thread '<main>' panicked at 'cargo rustc failed', /home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.67/src/lib.rs:131
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error:
```

Is cargo's error handling here just ugly?

**Comment by brson** [comment]
The panick message and empty 'error:' line are what bug me most.

**Comment by Manishearth** [comment]
It shouldn't be panicking, basically. We shell out to cargo, but we should exit gracefully.

**Comment by Manishearth** [comment]
Partial fix: https://github.com/Manishearth/rust-clippy/pull/936

**Comment by llogiq** [comment]
The other part is in cargo, I believe. We'd need a `cargo rustc --all -- ..` to compile libs + all binaries.

**Comment by oli-obk** [comment]
Well, technically we can call `cargo build` and inject the args with RUSTFLAGS. But that's pretty hacky... Not that cargo clippy isn't hacky ^^

**Comment by Manishearth** [comment]
The fix seems to be to use `cargo metadata --no-deps` and pick up the targets from there
