### ISSUE TITLE
Lock file error (OS X)

### ISSUE THREAD

**Issue by Kerosene2000** [Manishearth/rust-clippy#943]
For the moment I am fighting with `multirust`/`rust`/`cargo`, trying to compile `rust-clippy` in nightly 😢 
I get this f*cking error, and don't know why (stable works fine but I need nightly)
```bash
error: failed to lock file: /.../Documents/rust-clippy/Cargo.lock

Caused by:
  Operation not supported (os error 45)
```

**Comment by oli-obk** [comment]
Have you checked if there are any `cargo` or `rustc` processes still running? Maybe they crashed/froze. Not sure if OSX has that, but try `killall cargo` until you get something like `no processes found`. Then delete the `Cargo.lock` and try again with `cargo build`.

**Comment by Kerosene2000** [comment]
There were no processes still running (`killall cargo/rust`) and when I delete the `Cargo.lock` file, I get this error:
```bash
error: Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to lock file: /.../.multirust/toolchains/nightly/cargo/registry/index/github.com-1ecc6299db9ec823/.cargo-index-lock

Caused by:
  Operation not supported (os error 45)
```

**Comment by oli-obk** [comment]
have you run multirust or cargo with root at any point? that might have ended up creating files owned by root and thus you can't access them now.

**Comment by Kerosene2000** [comment]
No, never I don't have the root permissions.
That's not a permission problem, I think, because if I use a stable `rust` version (`multirust override stable`), the compilation starts and I get no errors until compiling `Clippy` itself...
[stable cargo build output](http://hastebin.com/adebopuzos.bash)

**Comment by Kerosene2000** [comment]
Ho and I am on `an nfs file system` if that can help...

**Comment by mcarton** [comment]
This does not look like it’s Clippy’s fault. Cargo [has had some problems with nfs on apparently, and it has been “fixed” on Linux, but not OS X](https://github.com/rust-lang/cargo/pull/2623). Maybe you should report it there.

**Comment by Kerosene2000** [comment]
By adding this link here, this issue is now visible on the this Cargo issue 👍

**Comment by mcarton** [comment]
> That's not a permission problem, I think, because if I use a stable `rust` version (`multirust override stable`), the compilation starts and I get no errors until compiling `Clippy` itself...
[stable cargo build output](http://hastebin.com/adebopuzos.bash)

Clippy can’t be built nor used with a non-nightly compiler.

**Comment by Kerosene2000** [comment]
Yup, but `cargo`/`rust` starts the compilation and give me [these logic errors](http://hastebin.com/adebopuzos.bash).

**Comment by mcarton** [comment]
Closing as Cargo’s team has made a PR for that. Feel free to open an new issue if anything is still wrong after it has been merged.
