### ISSUE TITLE
Build fail 0.0.68

### ISSUE THREAD

**Issue by Yamakaky** [Manishearth/rust-clippy#946]
https://travis-ci.org/crabtw/rust-bindgen/jobs/132243299
Any idea where it comes from?

**Comment by oli-obk** [comment]
it's being fixed: #944

but it's really hard this time :)

**Comment by Yamakaky** [comment]
Cool, I'll test it.

**Comment by Yamakaky** [comment]
Please notify me when the new version is on crates.io

**Comment by mcarton** [comment]
Published new 0.0.69 version.

**Comment by Yamakaky** [comment]
Cool
