### ISSUE TITLE
shadowing primitive types

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#949]
It's legal in beta/nightly to shadow primitive types. I don't think this is useful to have, but it was decided to do this for forward compatibility with `u128` and potentially other new primitive types. Clippy could lint against any type declarations or generic arguments that shadow a primitive

**Comment by mcarton** [comment]
Related: https://stackoverflow.com/questions/37410672/rust-compiler-can-not-understand-same-types

**Comment by mcarton** [comment]
And another one: https://stackoverflow.com/questions/38526842/rust-hiding-and-receiving-generic-t-objects
This seems like something that could be useful!

**Comment by mcarton** [comment]
And now there is a Rust issue for that problem: https://github.com/rust-lang/rust/issues/35030.
