### ISSUE TITLE
Range::step_by(0)

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#95]
This currently doesn't even panic, but happily loops forever. Well, unless it is clipped with `.take(_)` or some such.

**Comment by Manishearth** [comment]
We should probably have a single file which handles all lints which ban a type, function, or method

**Comment by llogiq** [comment]
Yeah, this should probably be in the same LintPass as #96.

**Comment by Manishearth** [comment]
Actually, no, #96 is a pure AST match, whereas all of these (Option::unwrap, Range::step_by(0)) are middle-based checks that need to use expr_ty and match_def_path

**Comment by llogiq** [comment]
Most ranges will be defined in the same line of code as their `.step_by(..)`, so even if we don't use middle and just match either `ExprMethodCall{step_by, [ExprRange{Lit(from), Lit(to)}, ref step]}` or just `ExprRange{..}` without `step_by` (simplified here), we can probably catch a good percentage of occurrences.

We would need const folding for the check anyway (because the type won't tell us the range boundaries), so `expr_ty` would give us no benefit whatsoever.

**Comment by Manishearth** [comment]
No, I meant that all of these "ban a method" etc use `expr_ty` and `match_def_path` in a uniform way, which we can do all at once in a single place. (That's how I'm proposing this be organized, at least)

**Comment by llogiq** [comment]
I agree wholeheartedly with your organization, but I think you've misclassified this issue. As I said, this should be a pure AST match + const folding.

**Comment by Manishearth** [comment]
Oh, you intend for this lint to only work on range literals?

Works for me!

**Comment by Manishearth** [comment]
Note: Using T-AST for lints which need const folding but are otherwise pure AST

**Comment by llogiq** [comment]
Full ack. Once we have the const folding separated out into a `utils` method, there's no challenge in using it anyway :smile:

**Comment by nweston** [comment]
I'm going to take a stab at this today.

My plan is to warn on any use of `step_by(0)`. Even if there's a subsequent call to `.take(_)` or similar that prevents an infinite loop, `std::iter::repeat` is preferable. So I can't think of any case where `step_by(0)` is a good idea.

Are there any examples of how to do constant folding?

**Comment by Manishearth** [comment]
Ignore the constant folding for a bit, that will be available once @llogiq's stuff merges. Match on literal zeroes and leave a FIXME comment about constant folding
